import type { CompanyInvitationEmailProps, RenderedEmail, RewardUnlockedEmailProps, RoleChangedEmailProps, SystemNotificationEmailProps, UserAddedToCompanyEmailProps, WelcomeEmailProps } from "./types.ts";

const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]!);
const safeUrl = (value: string) => { const url = new URL(value); if (!['http:', 'https:'].includes(url.protocol)) throw new Error("INVALID_EMAIL_URL"); return url.toString() };
const roleName = (role: string) => ({company_owner:"Dono",admin:"Administrador",employee:"Funcionário",manager:"Gerente",financial:"Financeiro",viewer:"Visualizador",member:"Membro"})[role] ?? role;
const button = (label: string, url: string) => `<table role="presentation" cellspacing="0" cellpadding="0" style="margin:28px 0"><tr><td style="border-radius:10px;background:#2563eb"><a href="${escapeHtml(safeUrl(url))}" style="display:inline-block;padding:13px 22px;color:#fff;text-decoration:none;font-weight:700">${escapeHtml(label)}</a></td></tr></table>`;
const layout = (greeting: string, content: string) => `<!doctype html><html><body style="margin:0;background:#f4f7fb;font-family:Arial,sans-serif;color:#172033"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;margin:auto;background:#fff;border-radius:18px;overflow:hidden"><tr><td style="padding:24px 30px;background:#0b1f3a;color:#fff;font-size:22px;font-weight:800">VERTEX <span style="color:#60a5fa">HUB</span></td></tr><tr><td style="padding:34px 30px"><h1 style="margin:0 0 20px;font-size:24px;color:#0b1f3a">${escapeHtml(greeting)}</h1>${content}</td></tr><tr><td style="padding:22px 30px;background:#eef4fb;color:#526175;font-size:12px;line-height:1.6">Vertex Hub — Soluções digitais para empresas.<br>Este é um e-mail automático enviado pelo Vertex Hub.</td></tr></table></td></tr></table></body></html>`;
const paragraph = (value: string) => `<p style="margin:0 0 16px;line-height:1.65;color:#40516a">${escapeHtml(value)}</p>`;

export const welcomeEmail = ({name,appUrl}:WelcomeEmailProps):RenderedEmail => ({subject:"Bem-vindo ao Vertex Hub",html:layout(`Olá, ${name}.`,paragraph("Bem-vindo ao Vertex Hub. Sua conta foi criada com sucesso.")+paragraph("Agora você pode acessar sua empresa e utilizar os recursos disponíveis para o seu perfil.")+button("Acessar Vertex Hub",appUrl)),text:`Olá, ${name}. Bem-vindo ao Vertex Hub. Acesse: ${appUrl}`});
export const userAddedToCompanyEmail = ({name,companyName,role,actorName,appUrl}:UserAddedToCompanyEmailProps):RenderedEmail => ({subject:`Você foi adicionado à ${companyName}`,html:layout(`Olá, ${name}.`,paragraph(`Você foi adicionado à empresa ${companyName}.`)+paragraph(`Cargo: ${roleName(role)}.${actorName?` Ação realizada por ${actorName}.`:""}`)+button("Acessar Vertex Hub",appUrl)),text:`Olá, ${name}. Você foi adicionado à empresa ${companyName} como ${roleName(role)}. Acesse: ${appUrl}`});
export const companyInvitationEmail = ({companyName,role,invitationUrl}:CompanyInvitationEmailProps):RenderedEmail => ({subject:`Convite para entrar na ${companyName}`,html:layout("Olá.",paragraph(`Você recebeu um convite para entrar na empresa ${companyName}.`)+paragraph(`Cargo previsto: ${roleName(role)}.`)+button("Aceitar convite",invitationUrl)),text:`Você recebeu um convite para entrar na empresa ${companyName} como ${roleName(role)}. Aceite: ${invitationUrl}`});
export const roleChangedEmail = ({name,companyName,role,appUrl}:RoleChangedEmailProps):RenderedEmail => ({subject:`Seu acesso na ${companyName} foi alterado`,html:layout(`Olá, ${name}.`,paragraph(`Seu nível de acesso na empresa ${companyName} foi alterado.`)+paragraph(`Novo cargo: ${roleName(role)}.`)+button("Acessar Vertex Hub",appUrl)),text:`Olá, ${name}. Seu novo cargo na ${companyName} é ${roleName(role)}. Acesse: ${appUrl}`});
export const rewardUnlockedEmail = ({name,rewardName,appUrl}:RewardUnlockedEmailProps):RenderedEmail => ({subject:"Nova conquista desbloqueada",html:layout(`Olá, ${name}.`,paragraph(`Você desbloqueou: ${rewardName}.`)+paragraph("Obrigado por apoiar o projeto.")+button("Ver meu perfil",appUrl)),text:`Olá, ${name}. Você desbloqueou ${rewardName}. Veja seu perfil: ${appUrl}`});
export const systemNotificationEmail = ({title,message,buttonText,buttonUrl}:SystemNotificationEmailProps):RenderedEmail => ({subject:title,html:layout(title,paragraph(message)+(buttonText&&buttonUrl?button(buttonText,buttonUrl):"")),text:`${title}\n\n${message}${buttonText&&buttonUrl?`\n\n${buttonText}: ${buttonUrl}`:""}`});
