import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const MIN=5,MAX=1000;
const safeText=(v:unknown,max:number)=>String(v??"").replace(/[<>\u0000-\u001f]/g,"").trim().slice(0,max);
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"method_not_allowed"},405);try{
 const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,token=Deno.env.get("MERCADO_PAGO_ACCESS_TOKEN")??"",mode=Deno.env.get("MERCADO_PAGO_MODE")??"test";
 if(mode!=="test")return json({error:"production_disabled"},503);if(!token)return json({error:"integration_not_configured"},503);
 const authorization=req.headers.get("Authorization")??"";const callerClient=createClient(url,anon,{global:{headers:{Authorization:authorization}}});const admin=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const{data:{user}}=await callerClient.auth.getUser();if(!user)return json({error:"unauthorized"},401);
 const body=await req.json(),action=String(body.action??"create");
 if(action==="config"){const{data:profile}=await admin.from("profiles").select("global_role,authorized_company_id").eq("user_id",user.id).single();let allowed=profile?.global_role==="super_admin";if(!allowed&&profile?.authorized_company_id){const{data:m}=await admin.from("company_members").select("role").eq("company_id",profile.authorized_company_id).eq("user_id",user.id).maybeSingle();allowed=m?.role==="company_owner"}if(!allowed)return json({error:"forbidden"},403);const{data:rows}=await admin.from("support_payments").select("id,user_id,mercado_pago_order_id,external_reference,amount,payment_method,order_status,transaction_status,status_detail,environment,created_at").order("created_at",{ascending:false}).limit(50);return json({mode,publicKeyConfigured:Boolean(Deno.env.get("MERCADO_PAGO_PUBLIC_KEY")),accessTokenConfigured:Boolean(token),webhookSecretConfigured:Boolean(Deno.env.get("MERCADO_PAGO_WEBHOOK_SECRET")),orders:rows??[]});}
 if(action==="get"){const id=safeText(body.id,80);const{data}=await admin.from("support_payments").select("id,mercado_pago_order_id,external_reference,amount,currency,payment_method,order_status,transaction_status,status_detail,environment,live_mode,created_at,paid_at,raw_safe_response").eq("id",id).eq("user_id",user.id).single();return data?json({payment:data}):json({error:"not_found"},404)}
 const amount=Number(body.amount),currency=String(body.currency??"BRL"),clientRequestId=String(body.client_request_id??"");if(!Number.isFinite(amount)||amount<MIN||amount>MAX||Math.round(amount*100)!==amount*100||currency!=="BRL"||!/^[0-9a-f-]{36}$/i.test(clientRequestId))return json({error:"invalid_input"},400);
 const{data:existing}=await admin.from("support_payments").select("id,mercado_pago_order_id,order_status,transaction_status").eq("user_id",user.id).eq("client_request_id",clientRequestId).maybeSingle();if(existing)return json({payment:existing,reused:true});
 const id=crypto.randomUUID(),idempotency=crypto.randomUUID(),external=`support_${id}`,message=safeText(body.message,200),isPublic=body.is_public===true;const{data:profile}=await admin.from("profiles").select("authorized_company_id").eq("user_id",user.id).single();
 const{error:insertError}=await admin.from("support_payments").insert({id,user_id:user.id,company_id:profile?.authorized_company_id??null,client_request_id:clientRequestId,external_reference:external,idempotency_key:idempotency,amount,currency,message:message||null,is_public:isPublic,environment:"test",live_mode:false});if(insertError)return json({error:"request_conflict"},409);
 const f=body.form_data??{},method=String(f.payment_method_id??""),type=String(f.payment_type_id??"");const paymentMethod:any={id:method,type};if(f.token)paymentMethod.token=String(f.token);if(Number(f.installments)>0)paymentMethod.installments=Number(f.installments);
 const orderBody={type:"online",processing_mode:"automatic",external_reference:external,total_amount:amount.toFixed(2),payer:{email:user.email,first_name:"APRO"},transactions:{payments:[{amount:amount.toFixed(2),payment_method:paymentMethod}]}};
 const mp=await fetch("https://api.mercadopago.com/v1/orders",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json","X-Idempotency-Key":idempotency},body:JSON.stringify(orderBody)});const order=await mp.json();if(!mp.ok){const providerDetail=safeText(order?.error??order?.message??order?.errors?.map((x:any)=>`${x.code??"error"}: ${x.message??"invalid"} ${typeof x.details==="string"?x.details:JSON.stringify(x.details??{})}`).join(" | ")??`http_${mp.status}`,500);console.error("mercadopago order",external,mp.status,providerDetail);await admin.from("support_payments").update({payment_method:method||null,order_status:"failed",status_detail:providerDetail,updated_at:new Date().toISOString()}).eq("id",id);return json({error:"provider_error",detail:providerDetail},502)}
 const transaction=order.transactions?.payments?.[0]??{};if(order.live_mode===true){await admin.from("support_payments").update({order_status:"blocked_live_order",live_mode:true,updated_at:new Date().toISOString()}).eq("id",id);return json({error:"live_order_blocked"},502)}
 const safe={transaction_id:transaction.id,pix_qr_code:transaction.payment_method?.qr_code,pix_qr_code_base64:transaction.payment_method?.qr_code_base64,ticket_url:transaction.payment_method?.ticket_url};await admin.from("support_payments").update({mercado_pago_order_id:String(order.id),payment_method:method,order_status:order.status??"processing",transaction_status:transaction.status??null,status_detail:transaction.status_detail??null,live_mode:false,raw_safe_response:safe,updated_at:new Date().toISOString()}).eq("id",id);console.log("mercadopago order",order.id,external,order.status);return json({payment:{id,order_id:order.id,external_reference:external,status:order.status,transaction_status:transaction.status,transaction_id:transaction.id,pix:safe}});
}catch(error){console.error("mercadopago-orders",error instanceof Error?error.message:"unknown");return json({error:"internal_error"},500)}});
