import { supabase } from "./supabase";
export type PasskeyItem={id:string;friendly_name?:string;created_at:string;last_used_at?:string};
export const supportsPasskeys=()=>typeof window!=="undefined"&&"PublicKeyCredential" in window&&window.isSecureContext;
const cancelled=(error:unknown)=>{const e=error as {name?:string;message?:string;code?:string};return e?.name==="NotAllowedError"||/cancel|abort|notallowed/i.test(`${e?.code??""} ${e?.message??""}`)};
export function passkeyError(error:unknown){if(cancelled(error))return{message:"Autenticação cancelada.",cancelled:true};const e=error as{code?:string;message?:string};const code=e?.code??"";const messages:Record<string,string>={passkey_disabled:"As chaves de acesso ainda não foram habilitadas neste projeto.",too_many_passkeys:"Você atingiu o limite de chaves de acesso desta conta.",webauthn_credential_exists:"Esta chave de acesso já está cadastrada nesta conta.",webauthn_credential_not_found:"Esta chave de acesso não foi encontrada.",webauthn_challenge_not_found:"A solicitação expirou ou já foi utilizada. Tente novamente.",webauthn_challenge_expired:"A solicitação expirou. Tente novamente.",webauthn_verification_failed:"Não foi possível verificar esta chave de acesso.",email_not_confirmed:"Confirme seu e-mail antes de usar uma chave de acesso.",phone_not_confirmed:"Confirme seu telefone antes de usar uma chave de acesso.",user_banned:"Esta conta está bloqueada."};return{message:messages[code]??"Não foi possível concluir a operação com a chave de acesso.",cancelled:false}}
export async function signInWithPasskey(){if(!supportsPasskeys())return{error:"Este navegador ou dispositivo não oferece suporte a chaves de acesso."};try{const{error}=await supabase.auth.signInWithPasskey();return error?{error:passkeyError(error).message}:{}}catch(error){return{error:passkeyError(error).message}}}
export async function listPasskeys(){const{data,error}=await supabase.auth.passkey.list();if(error)throw error;return(data??[])as PasskeyItem[]}
export async function registerPasskey(){const{error}=await supabase.auth.registerPasskey();if(error)throw error}
export async function renamePasskey(passkeyId:string,friendlyName:string){const name=friendlyName.trim();if(!name||name.length>120)throw new Error("O nome deve ter entre 1 e 120 caracteres.");const{error}=await supabase.auth.passkey.update({passkeyId,friendlyName:name});if(error)throw error}
export async function deletePasskey(passkeyId:string){const{error}=await supabase.auth.passkey.delete({passkeyId});if(error)throw error}
