import { createContext,useCallback,useContext,useEffect,useMemo,useState } from "react";
import { supabase } from "../services/supabase";
import type { Company,Profile } from "../types";
import { useAuth } from "./AuthContext";
type Value={profile:Profile|null;companies:Company[];activeCompany:Company|null;loading:boolean;isAdmin:boolean;selectCompany:(id:string)=>void;reload:()=>Promise<void>};
const Context=createContext<Value|null>(null);
type ProfileRow={user_id:string;full_name:string;email:string;phone:string|null;cpf:string|null;avatar_url:string|null;global_role:Profile["globalRole"];onboarding_completed:boolean};
type CompanyRow={id:string;name:string;legal_name:string|null;cnpj:string|null;phone:string|null;email:string|null;logo_url:string|null;status:Company["status"];created_at:string};
const company=(r:CompanyRow):Company=>({id:r.id,name:r.name,legalName:r.legal_name??undefined,cnpj:r.cnpj??undefined,phone:r.phone??undefined,email:r.email??undefined,logoUrl:r.logo_url??undefined,status:r.status,createdAt:r.created_at});
export function CompanyProvider({children}:{children:React.ReactNode}){const{user}=useAuth();const[profile,setProfile]=useState<Profile|null>(null),[companies,setCompanies]=useState<Company[]>([]),[activeCompany,setActive]=useState<Company|null>(null),[loading,setLoading]=useState(true);
 const reload=useCallback(async()=>{if(!user){setLoading(false);return}setLoading(true);const{data:p}=await supabase.from("profiles").select("*").eq("user_id",user.id).maybeSingle();if(!p){setProfile(null);setCompanies([]);setActive(null);setLoading(false);return}const r=p as ProfileRow;const mapped:Profile={userId:r.user_id,fullName:r.full_name,email:r.email,phone:r.phone??undefined,cpf:r.cpf??undefined,avatarUrl:r.avatar_url??undefined,globalRole:r.global_role,onboardingCompleted:r.onboarding_completed};setProfile(mapped);const admin=r.global_role==="admin"||r.global_role==="super_admin";const q=admin?supabase.from("companies").select("*").order("name"):supabase.from("companies").select("*, company_members!inner(user_id)").eq("company_members.user_id",user.id).order("name");const{data}=await q;const list=((data??[])as unknown as CompanyRow[]).map(company);setCompanies(list);const stored=sessionStorage.getItem("vertex-active-company");setActive(list.find(x=>x.id===stored)??list[0]??null);setLoading(false)},[user]);
 useEffect(()=>{void reload()},[reload]);const selectCompany=(id:string)=>{const found=companies.find(x=>x.id===id);if(found){sessionStorage.setItem("vertex-active-company",id);setActive(found)}};const value=useMemo(()=>({profile,companies,activeCompany,loading,isAdmin:profile?.globalRole==="admin"||profile?.globalRole==="super_admin",selectCompany,reload}),[profile,companies,activeCompany,loading,reload]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useCompany=()=>{const v=useContext(Context);if(!v)throw new Error("CompanyProvider ausente");return v};
