import { createContext,useCallback,useContext,useEffect,useMemo,useState } from "react";
import { supabase } from "../services/supabase";
import type { Company,CompanyRole,Profile } from "../types";
import { useAuth } from "./AuthContext";
type Value={profile:Profile|null;companies:Company[];activeCompany:Company|null;companyRole:CompanyRole|null;loading:boolean;isAdmin:boolean;isSuperAdmin:boolean;selectCompany:(id:string)=>void;reload:()=>Promise<void>};
const Context=createContext<Value|null>(null);
type ProfileRow={user_id:string;full_name:string;email:string;phone:string|null;cpf:string|null;avatar_url:string|null;global_role:Profile["globalRole"];onboarding_completed:boolean};
type CompanyRow={id:string;name:string;legal_name:string|null;cnpj:string|null;phone:string|null;email:string|null;logo_url:string|null;status:Company["status"];plan:Company["plan"];created_at:string;enterprise_user_limit:number|null;enterprise_storage_gb:number|null;enterprise_financial_assistance:boolean;enterprise_notes:string|null};
const company=(r:CompanyRow):Company=>({id:r.id,name:r.name,legalName:r.legal_name??undefined,cnpj:r.cnpj??undefined,phone:r.phone??undefined,email:r.email??undefined,logoUrl:r.logo_url??undefined,status:r.status,plan:r.plan??"free",createdAt:r.created_at,enterpriseUserLimit:r.enterprise_user_limit??undefined,enterpriseStorageGb:r.enterprise_storage_gb??undefined,enterpriseFinancialAssistance:r.enterprise_financial_assistance,enterpriseNotes:r.enterprise_notes??undefined});
export function CompanyProvider({children}:{children:React.ReactNode}){const{user}=useAuth();const[profile,setProfile]=useState<Profile|null>(null),[companies,setCompanies]=useState<Company[]>([]),[activeCompany,setActive]=useState<Company|null>(null),[companyRole,setCompanyRole]=useState<CompanyRole|null>(null),[loading,setLoading]=useState(true);
 const reload=useCallback(async()=>{if(!user){setLoading(false);return}setLoading(true);const{data:p}=await supabase.from("profiles").select("*").eq("user_id",user.id).maybeSingle();if(!p){setProfile(null);setCompanies([]);setActive(null);setLoading(false);return}const r=p as ProfileRow;const mapped:Profile={userId:r.user_id,fullName:r.full_name,email:r.email,phone:r.phone??undefined,cpf:r.cpf??undefined,avatarUrl:r.avatar_url??undefined,globalRole:r.global_role,onboardingCompleted:r.onboarding_completed};setProfile(mapped);const superAdmin=r.global_role==="super_admin";const q=superAdmin?supabase.from("companies").select("*").order("name"):supabase.from("companies").select("*, company_members!inner(user_id)").eq("company_members.user_id",user.id).order("name");const[{data},{data:memberships}]=await Promise.all([q,supabase.from("company_members").select("company_id,role").eq("user_id",user.id)]);const list=((data??[])as unknown as CompanyRow[]).map(company);setCompanies(list);const stored=sessionStorage.getItem("vertex-active-company");const selected=list.find(x=>x.id===stored)??list[0]??null;setActive(selected);const membership=(memberships??[]).find(m=>m.company_id===selected?.id);setCompanyRole((membership?.role as CompanyRole)??null);setLoading(false)},[user]);
 useEffect(()=>{void reload()},[reload]);const selectCompany=(id:string)=>{const found=companies.find(x=>x.id===id);if(found){sessionStorage.setItem("vertex-active-company",id);setActive(found);void supabase.from("company_members").select("role").eq("company_id",id).eq("user_id",user?.id??"").maybeSingle().then(({data})=>setCompanyRole((data?.role as CompanyRole)??null))}};const isSuperAdmin=profile?.globalRole==="super_admin";const isAdmin=isSuperAdmin||companyRole==="company_owner"||companyRole==="admin";const value=useMemo(()=>({profile,companies,activeCompany,companyRole,loading,isAdmin,isSuperAdmin,selectCompany,reload}),[profile,companies,activeCompany,companyRole,loading,isAdmin,isSuperAdmin,reload]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useCompany=()=>{const v=useContext(Context);if(!v)throw new Error("CompanyProvider ausente");return v};
