type LegalType="privacy"|"terms";
type Section={title:string;paragraphs:string[]};
const privacy:Section[]=[
 {title:"Introdução, identidade e escopo",paragraphs:["Esta Política explica como o Vertex Hub trata dados pessoais durante o cadastro, autenticação e uso da plataforma empresarial. Ela se aplica aos usuários, representantes de empresas, administradores e funcionários vinculados.","A Vertex disponibiliza o Vertex Hub como plataforma SaaS de gestão. Conforme o contexto, a Vertex poderá atuar como controladora dos dados necessários à conta e segurança, enquanto a empresa cadastrada poderá ser controladora dos dados empresariais inseridos por seus usuários."]},
 {title:"Dados fornecidos diretamente",paragraphs:["Podemos tratar nome, e-mail, telefone, CPF quando informado, credenciais protegidas pelo provedor de autenticação, preferências e informações enviadas em solicitações de atendimento.","Os dados da empresa podem incluir nome empresarial, nome fantasia, CNPJ, e-mail, telefone e informações de operação. Dados de funcionários abrangem identificação, vínculo, cargo e nível de acesso definidos pela empresa."]},
 {title:"Dados técnicos, acesso e segurança",paragraphs:["Podem ser tratados endereço IP, data e horário de acesso, navegador, sistema operacional, identificadores de sessão, dispositivo, eventos de autenticação e logs necessários à prevenção de fraude e investigação de incidentes.","Senhas são processadas pelo serviço de autenticação. Login social e Passkeys podem envolver provedores terceiros. O Vertex Hub não recebe a biometria nem a chave privada utilizada por uma Passkey."]},
 {title:"Finalidades do tratamento",paragraphs:["Os dados são utilizados para criar e manter contas, autenticar usuários, aplicar permissões, vincular pessoas a empresas, operar recursos contratados, prestar suporte, manter registros de auditoria, prevenir abuso, corrigir falhas e cumprir obrigações legais ou regulatórias."]},
 {title:"Bases legais",paragraphs:["Conforme a atividade, o tratamento poderá se apoiar na execução de contrato ou procedimentos preliminares, cumprimento de obrigação legal, exercício regular de direitos, legítimo interesse avaliado de forma responsável e consentimento quando essa for a base adequada, nos termos da LGPD."]},
 {title:"Autenticação e controle de acesso",paragraphs:["A plataforma utiliza autenticação, isolamento por empresa e regras de acesso no banco de dados. Donos, administradores e funcionários possuem permissões diferentes. A empresa é responsável por revisar seus vínculos e remover acessos que deixem de ser necessários."]},
 {title:"Compartilhamento e prestadores",paragraphs:["Dados não são vendidos. Informações podem ser compartilhadas com prestadores essenciais de hospedagem, banco de dados, autenticação, comunicação, monitoramento e suporte, limitadas ao necessário para a operação e sujeitas às condições aplicáveis."]},
 {title:"Armazenamento e transferências",paragraphs:["A infraestrutura pode utilizar provedores com processamento no Brasil ou no exterior. Quando houver transferência internacional, serão consideradas as salvaguardas e requisitos aplicáveis. A localização e os fornecedores podem mudar conforme a evolução técnica do serviço."]},
 {title:"Retenção",paragraphs:["Os dados são mantidos pelo período necessário ao funcionamento da conta, às finalidades informadas, à segurança, à auditoria e ao cumprimento de obrigações. Após encerramento ou solicitação válida, dados poderão ser excluídos ou anonimizados, ressalvadas hipóteses legais de conservação."]},
 {title:"Segurança da informação",paragraphs:["São adotadas medidas técnicas e administrativas proporcionais aos riscos, como autenticação, registros de eventos e controles por empresa. Nenhum ambiente é imune a incidentes; por isso, usuários também devem proteger credenciais, dispositivos e sessões."]},
 {title:"Cookies e tecnologias semelhantes",paragraphs:["O Vertex Hub pode utilizar armazenamento local e tecnologias necessárias para sessão, preferências, tema, segurança e funcionamento. Caso sejam adotadas tecnologias não essenciais, informações e escolhas adicionais poderão ser apresentadas."]},
 {title:"Direitos dos titulares",paragraphs:["Nos termos da LGPD, o titular pode solicitar confirmação e acesso, correção, anonimização, bloqueio ou exclusão quando cabíveis, portabilidade conforme regulamentação, informação sobre compartilhamento e revisão ou revogação de consentimento quando aplicável.","A solicitação poderá exigir validação de identidade. Alguns pedidos relacionados a dados empresariais precisarão ser direcionados à empresa responsável pelo conteúdo."]},
 {title:"Correção, exclusão e encerramento",paragraphs:["Dados pessoais editáveis podem ser corrigidos nas configurações ou por solicitação. A exclusão de conta e dados observará vínculos empresariais, registros de auditoria, obrigações legais e direitos de terceiros. A exclusão de um usuário não implica automaticamente a exclusão de dados cuja responsabilidade pertença à empresa."]},
 {title:"Empresas e usuários vinculados",paragraphs:["A empresa cadastrada determina quais informações seus usuários inserem e quem pode consultá-las. Ela deve possuir base legal para dados de clientes, funcionários e terceiros e orientar seus usuários sobre o tratamento realizado no Hub."]},
 {title:"Atualizações e contato",paragraphs:["Esta Política poderá ser atualizada para refletir mudanças legais, operacionais ou técnicas. Alterações relevantes serão comunicadas por meios razoáveis. Solicitações de privacidade devem ser encaminhadas pelo canal informado ao final deste documento."]},
];
const terms:Section[]=[
 {title:"Introdução e aceitação",paragraphs:["Estes Termos regulam o acesso e uso do Vertex Hub. Ao criar conta, aceitar os Termos ou utilizar a plataforma, o usuário declara ter capacidade para assumir estas condições e compromete-se a cumpri-las."]},
 {title:"Definições",paragraphs:["Vertex Hub é a plataforma SaaS empresarial; Conta é o cadastro individual autenticado; Empresa é o ambiente organizacional; Dono é a autoridade máxima da empresa; Administrador possui gestão operacional; Funcionário possui acesso de consulta; Chave de ativação libera o vínculo e não se confunde com Passkey."]},
 {title:"Cadastro e informações",paragraphs:["O usuário deve fornecer informações verdadeiras, atuais e suficientes. A empresa e seus representantes respondem pela legitimidade dos dados inseridos e pela autorização de pessoas vinculadas."]},
 {title:"Segurança da conta",paragraphs:["Credenciais são pessoais e não devem ser compartilhadas. O usuário deve comunicar suspeitas de acesso indevido. Senhas, MFA/TOTP quando disponível e Passkeys são mecanismos de autenticação; cada usuário é responsável pela segurança de seus dispositivos e fatores."]},
 {title:"Chaves de ativação",paragraphs:["Chaves de ativação são códigos de autorização emitidos pela Vertex ou por administradores habilitados. Devem ser usadas somente pela pessoa e empresa às quais se destinam. Chaves usadas, expiradas, canceladas, incompatíveis ou de outra empresa serão recusadas."]},
 {title:"Vínculos, perfis e permissões",paragraphs:["O Dono mantém a autoridade máxima da empresa. O Administrador pode gerenciar operações conforme as permissões vigentes, sem assumir automaticamente prerrogativas exclusivas do Dono. O Funcionário possui acesso somente leitura aos dados da empresa vinculada."]},
 {title:"Uso permitido",paragraphs:["A plataforma deve ser utilizada para finalidades empresariais lícitas, respeitando direitos de terceiros, contratos, políticas internas e legislação aplicável."]},
 {title:"Uso proibido",paragraphs:["É proibido invadir ou testar sistemas sem autorização, explorar vulnerabilidades, contornar permissões, acessar outra empresa, introduzir código malicioso, automatizar abuso, compartilhar credenciais indevidamente ou utilizar o serviço para atividade ilícita."]},
 {title:"Conteúdo e responsabilidade da empresa",paragraphs:["Usuários e empresas permanecem responsáveis pelo conteúdo inserido, sua exatidão, licitude, retenção e permissões. O Vertex Hub não se torna proprietário dos dados empresariais pelo simples armazenamento necessário à prestação do serviço."]},
 {title:"Funcionalidades e terceiros",paragraphs:["Funcionalidades podem depender de serviços terceiros, como autenticação, hospedagem e login social. Termos e disponibilidade desses prestadores também podem afetar a experiência."]},
 {title:"Disponibilidade, manutenção e mudanças",paragraphs:["A Vertex busca manter o serviço disponível, mas interrupções, manutenções e eventos fora de controle razoável podem ocorrer. Recursos podem ser corrigidos, aprimorados, substituídos ou descontinuados mediante avaliação de impacto e comunicação quando apropriado."]},
 {title:"Planos e recursos",paragraphs:["Quando houver planos, licenças ou recursos condicionados, as condições comerciais aplicáveis serão apresentadas separadamente. Estes Termos não criam cobrança ou garantia de funcionalidade não contratada."]},
 {title:"Suspensão e encerramento",paragraphs:["Acesso pode ser suspenso por risco de segurança, ordem legal, violação destes Termos, uso abusivo ou encerramento da relação. O usuário pode solicitar encerramento, sujeito à validação e às regras de retenção e vínculos empresariais."]},
 {title:"Exclusão de dados",paragraphs:["Pedidos de exclusão serão avaliados conforme a Política de Privacidade, responsabilidades da empresa, direitos de terceiros e obrigações de retenção. O Dono deve considerar a continuidade operacional antes de excluir informações empresariais."]},
 {title:"Propriedade intelectual",paragraphs:["A marca Vertex, o software, a interface, elementos visuais, documentação e materiais próprios são protegidos. Estes Termos concedem apenas autorização limitada de uso da plataforma, sem transferência de propriedade intelectual."]},
 {title:"Responsabilidades e limitações",paragraphs:["Cada parte responde por seus atos nos limites da legislação. A Vertex não responde por decisões tomadas exclusivamente com base em dados incorretos inseridos pelo usuário, uso indevido de credenciais ou indisponibilidade causada por terceiros fora de controle razoável, sem excluir responsabilidades que legalmente não possam ser limitadas."]},
 {title:"Privacidade",paragraphs:["O tratamento de dados pessoais é descrito na Política de Privacidade, que integra a compreensão destes Termos. Usuários e empresas devem observar suas próprias obrigações de proteção de dados."]},
 {title:"Alterações, legislação e contato",paragraphs:["Os Termos podem ser atualizados por razões legais, técnicas ou operacionais. Aplica-se a legislação brasileira, preservados os direitos legalmente assegurados. Dúvidas podem ser enviadas ao canal indicado ao final."]},
];
export function TermsContent({type="terms",platformName="Vertex Hub",contact="",onSwitch=()=>undefined}:{type?:LegalType;platformName?:string;contact?:string;onSwitch?:(type:LegalType)=>void}){
 const sections=type==="privacy"?privacy:terms;
 return <article className="text-sm leading-relaxed text-zinc-600 dark:text-zinc-300"><header className="border-b pb-5 dark:border-zinc-800"><p className="font-semibold text-blue-600">{platformName}</p><h2 className="mt-1 text-2xl font-black text-zinc-950 dark:text-white">{type==="privacy"?"Política de Privacidade":"Termos de Uso"}</h2><p className="mt-2 text-xs text-zinc-500">Última atualização: 3 de agosto de 2026</p></header><details className="my-5 rounded-xl border p-4 dark:border-zinc-800" open><summary className="cursor-pointer font-bold">Índice de seções</summary><ol className="mt-3 grid gap-1 sm:grid-cols-2">{sections.map((section,index)=><li key={section.title}><a className="text-blue-600 hover:underline" href={`#legal-${type}-${index}`}>{index+1}. {section.title}</a></li>)}</ol></details><div className="space-y-7">{sections.map((section,index)=><section id={`legal-${type}-${index}`} className="scroll-mt-6" key={section.title}><h3 className="text-base font-bold text-zinc-950 dark:text-white">{index+1}. {section.title}</h3>{section.paragraphs.map(paragraph=><p className="mt-2" key={paragraph}>{paragraph}</p>)}</section>)}</div><footer className="mt-8 border-t pt-5 dark:border-zinc-800"><p><b>Canal de contato:</b> {contact||"consulte os canais oficiais disponibilizados pela Vertex"}.</p><button className="mt-3 font-semibold text-blue-600 hover:underline" onClick={()=>onSwitch(type==="privacy"?"terms":"privacy")}>Consultar {type==="privacy"?"os Termos de Uso":"a Política de Privacidade"}</button></footer></article>;
}
