import { Copy,MoreHorizontal,Pencil,Trash2 } from "lucide-react";
import { useState } from "react";
import { useFinance } from "../../contexts/FinanceContext";
import { usePermissions } from "../../hooks/usePermissions";
import type { Transaction } from "../../types";
import { formatDate } from "../../utils/format";
import { formatProtectedCurrency } from "../../utils/protectedFormat";
import { ConfirmModal } from "../modals/ConfirmModal";
import { Card } from "../ui/Common";
const statusLabel={paid:"Pago",pending:"Pendente",scheduled:"Agendado"};
export function TransactionList({items,onEdit,limit}:{items:Transaction[];onEdit:(t:Transaction)=>void;limit?:number}){
 const{deleteTransaction,duplicateTransaction,hiddenValues}=useFinance(),permissions=usePermissions(),[menu,setMenu]=useState<string|null>(null),[deleting,setDeleting]=useState<Transaction|null>(null),shown=limit?items.slice(0,limit):items;
 if(!shown.length)return <Card className="py-14 text-center"><p className="text-lg font-bold">Nenhuma transação encontrada</p><p className="mt-1 text-sm text-zinc-500">Não existem movimentações para os filtros selecionados.</p></Card>;
 return <><div className="overflow-visible rounded-2xl border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900"><div className="hidden grid-cols-[1.6fr_1fr_.8fr_.9fr_.7fr_40px] gap-4 border-b px-5 py-3 text-xs font-semibold uppercase tracking-wider text-zinc-400 dark:border-zinc-800 md:grid"><span>Descrição</span><span>Categoria</span><span>Data</span><span>Status</span><span className="text-right">Valor</span><span/></div>
 {shown.map(transaction=><div key={transaction.id} className="relative grid gap-3 border-b border-zinc-100 p-4 last:border-0 dark:border-zinc-800 md:grid-cols-[1.6fr_1fr_.8fr_.9fr_.7fr_40px] md:items-center md:gap-4 md:px-5"><div className="flex items-center gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-xl font-bold ${transaction.type==="income"?"bg-emerald-500/10 text-emerald-500":"bg-red-500/10 text-red-500"}`}>{transaction.type==="income"?"↗":"↘"}</span><div><p className="font-semibold">{transaction.description}</p><p className="text-xs text-zinc-500 md:hidden">{transaction.paymentMethod}</p></div></div><span className="hidden text-sm text-zinc-500 md:block">{transaction.category}</span><span className="hidden text-sm text-zinc-500 md:block">{formatDate(transaction.date)}</span><span><i className={`mr-2 inline-block size-2 rounded-full ${transaction.status==="paid"?"bg-emerald-500":transaction.status==="pending"?"bg-amber-500":"bg-blue-500"}`}/><span className="text-xs">{statusLabel[transaction.status]}</span></span><strong className={`absolute right-14 top-5 text-sm md:static md:text-right ${transaction.type==="income"?"text-emerald-500":"text-red-500"}`}>{transaction.type==="income"?"+":"−"} {formatProtectedCurrency(transaction.amount,hiddenValues)}</strong>{permissions.canWrite&&<button aria-label={`Ações de ${transaction.description}`} onClick={()=>setMenu(menu===transaction.id?null:transaction.id)} className="absolute right-4 top-4 rounded-lg p-2 hover:bg-zinc-100 dark:hover:bg-zinc-800 md:static"><MoreHorizontal size={18}/></button>}
 {permissions.canWrite&&menu===transaction.id&&<div className="absolute right-4 top-12 z-10 w-40 rounded-xl border bg-white p-1 shadow-xl dark:border-zinc-700 dark:bg-zinc-800">{[{Icon:Pencil,label:"Editar",fn:()=>onEdit(transaction)},{Icon:Copy,label:"Duplicar",fn:()=>void duplicateTransaction(transaction.id)},{Icon:Trash2,label:"Excluir",fn:()=>setDeleting(transaction)}].map(({Icon,label,fn})=><button key={label} onClick={()=>{fn();setMenu(null)}} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm hover:bg-zinc-100 dark:hover:bg-zinc-700"><Icon size={15}/>{label}</button>)}</div>}</div>)}</div>
 <ConfirmModal open={Boolean(deleting)&&permissions.canWrite} title="Excluir transação" description={`A transação “${deleting?.description??""}” será removida permanentemente.`} confirmLabel="Excluir" danger onClose={()=>setDeleting(null)} onConfirm={()=>deleting?deleteTransaction(deleting.id):Promise.resolve()}/></>;
}
