import { useEffect,useState } from "react";
import { supabase } from "../../services/supabase";
import { Button,Card,Input } from "../ui/Common";
type Row=Record<string,any>;
const order:Record<string,number>={free:0,start:1,growth:2,prime:3,enterprise:4};
const sortPlans=(items:Row[])=>[...items].sort((a,b)=>(order[a.plan]??99)-(order[b.plan]??99));
export function PlanSettingsEditor(){
 const[rows,setRows]=useState<Row[]>([]),[saving,setSaving]=useState(false);
 useEffect(()=>{void supabase.from("plan_settings").select("*").then(({data})=>setRows(sortPlans(data??[])))},[]);
 const update=(i:number,key:string,value:string)=>setRows(v=>v.map((r,j)=>j===i?{...r,[key]:value}:r));
 const save=async()=>{setSaving(true);const user=(await supabase.auth.getUser()).data.user;for(const r of rows){const enterprise=r.plan==="enterprise";await supabase.from("plan_settings").update({monthly_price:enterprise?null:r.monthly_price===""?null:Number(r.monthly_price),user_limit:r.user_limit===""?null:Number(r.user_limit),lifetime_base_price:enterprise?null:r.lifetime_base_price===""?null:Number(r.lifetime_base_price),discount_3_months:enterprise?0:Number(r.discount_3_months),discount_12_months:enterprise?0:Number(r.discount_12_months),discount_lifetime:enterprise?0:Number(r.discount_lifetime),description:r.description,updated_by:user?.id,updated_at:new Date().toISOString()}).eq("plan",r.plan)}setSaving(false)};
 return <Card className="mt-5"><h3 className="font-bold">Valores e limites dos planos</h3><p className="mt-1 text-sm text-zinc-500">O Enterprise é sempre personalizado e aparece por último.</p><div className="mt-5 space-y-5">{rows.map((r,i)=>{const enterprise=r.plan==="enterprise";return <div key={r.plan} className="rounded-xl border p-4 dark:border-zinc-700"><b className="uppercase text-blue-500">{r.display_name}</b>{enterprise?<p className="mt-3 rounded-xl bg-blue-500/10 p-3 text-sm text-blue-500">Valor, quantidade de usuários e condições definidos individualmente com a empresa.</p>:<div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label>Mensalidade<Input type="number" value={r.monthly_price??""} onChange={e=>update(i,"monthly_price",e.target.value)}/></label><label>Limite de usuários<Input type="number" value={r.user_limit??""} onChange={e=>update(i,"user_limit",e.target.value)}/></label><label>Base vitalícia<Input type="number" value={r.lifetime_base_price??""} onChange={e=>update(i,"lifetime_base_price",e.target.value)}/></label><label>Desconto 3 meses (%)<Input type="number" value={r.discount_3_months} onChange={e=>update(i,"discount_3_months",e.target.value)}/></label><label>Desconto 12 meses (%)<Input type="number" value={r.discount_12_months} onChange={e=>update(i,"discount_12_months",e.target.value)}/></label><label>Desconto vitalício (%)<Input type="number" value={r.discount_lifetime} onChange={e=>update(i,"discount_lifetime",e.target.value)}/></label></div>}<label className="mt-3 block">Descrição<Input value={r.description} onChange={e=>update(i,"description",e.target.value)}/></label></div>})}</div><Button disabled={saving} onClick={()=>void save()}>{saving?"Salvando...":"Salvar planos"}</Button></Card>
}
