import { Database,Save,ServerCog } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { Button,Card,Input,Select } from "../components/ui/Common";
import { useFinance } from "../contexts/FinanceContext";
import { supabase } from "../services/supabase";

type Setting={key:string;value:string};
type SystemForm={version:string;environment:string;database:string;status:string};
const defaults:SystemForm={version:"2.0.0",environment:"Produção",database:"Supabase",status:"Operacional"};
const systemKeys={version:"system_version",environment:"system_environment",database:"system_database",status:"system_status"} as const;
const labels:Record<string,string>={platform_name:"Nome da plataforma",commercial_email:"E-mail comercial",commercial_whatsapp:"WhatsApp comercial"};
const statusColor:Record<string,string>={Operacional:"bg-emerald-500",Manutenção:"bg-amber-500",Instabilidade:"bg-yellow-500",Indisponível:"bg-red-500"};

export function GlobalSettings(){
  const{notify}=useFinance();
  const[rows,setRows]=useState<Setting[]>([]),[system,setSystem]=useState<SystemForm>(defaults),[loading,setLoading]=useState(true),[savingGlobal,setSavingGlobal]=useState(false),[savingSystem,setSavingSystem]=useState(false);
  const systemNames=useMemo(()=>new Set<string>(Object.values(systemKeys)),[]);
  const load=async()=>{setLoading(true);const{data,error}=await supabase.from("global_settings").select("key,value").order("key");setLoading(false);if(error){notify("Não foi possível carregar as configurações.","error");return}const values=(data??[]) as Setting[];setRows(values.filter(row=>!systemNames.has(row.key)));const find=(key:string,fallback:string)=>values.find(row=>row.key===key)?.value??fallback;setSystem({version:find(systemKeys.version,defaults.version),environment:find(systemKeys.environment,defaults.environment),database:find(systemKeys.database,defaults.database),status:find(systemKeys.status,defaults.status)})};
  useEffect(()=>{void load()},[]);
  const saveGlobal=async()=>{if(savingGlobal)return;setSavingGlobal(true);const user=(await supabase.auth.getUser()).data.user;const results=await Promise.all(rows.map(row=>supabase.from("global_settings").update({value:row.value.trim(),updated_by:user?.id,updated_at:new Date().toISOString()}).eq("key",row.key)));setSavingGlobal(false);notify(results.some(result=>result.error)?"Não foi possível salvar as configurações. Tente novamente.":"Configurações salvas com sucesso",results.some(result=>result.error)?"error":"success")};
  const saveSystem=async()=>{if(savingSystem)return;setSavingSystem(true);const{error}=await supabase.rpc("admin_save_system_settings",{p_version:system.version.trim(),p_environment:system.environment.trim(),p_database:system.database.trim(),p_status:system.status});setSavingSystem(false);if(error){notify("Não foi possível salvar as configurações. Tente novamente.","error");return}notify("Configurações do sistema salvas com sucesso");await load()};
  const update=(key:keyof SystemForm,value:string)=>setSystem(current=>({...current,[key]:value}));
  return <><div className="mb-6"><p className="text-sm text-zinc-500">Plataforma</p><h2 className="text-3xl font-black">Configurações globais</h2></div><Card><div className="mb-5 flex gap-3"><ServerCog className="text-blue-500"/><div><h3 className="font-bold">Configurações da plataforma</h3><p className="text-sm text-zinc-500">Dados institucionais e canais globais.</p></div></div>{loading?<p className="text-sm text-zinc-500">Carregando configurações...</p>:<div className="grid gap-4 md:grid-cols-2">{rows.map((row,index)=><label key={row.key}>{labels[row.key]??row.key}<Input value={row.value} onChange={event=>setRows(current=>current.map((item,itemIndex)=>itemIndex===index?{...item,value:event.target.value}:item))}/></label>)}</div>}<Button className="mt-5" disabled={loading||savingGlobal} onClick={()=>void saveGlobal()}><Save size={16}/>{savingGlobal?"Salvando...":"Salvar configurações"}</Button></Card><Card className="mt-5"><div className="mb-5 flex gap-3"><Database className="text-violet-500"/><div><h3 className="font-bold">Configurações do sistema</h3><p className="text-sm text-zinc-500">Informações gerais da infraestrutura e versão atual do Vertex Hub.</p></div></div><div className="grid gap-4 md:grid-cols-2"><label>Versão<Input maxLength={32} value={system.version} onChange={event=>update("version",event.target.value)} placeholder="2.0.0"/></label><label>Ambiente<Input maxLength={80} value={system.environment} onChange={event=>update("environment",event.target.value)} placeholder="Produção"/></label><label>Banco de dados<Input maxLength={80} value={system.database} onChange={event=>update("database",event.target.value)} placeholder="Supabase"/></label><label>Status<div className="relative"><i className={`pointer-events-none absolute left-3 top-4 size-2 rounded-full ${statusColor[system.status]??"bg-zinc-400"}`}/><Select className="pl-8" value={system.status} onChange={event=>update("status",event.target.value)}><option>Operacional</option><option>Manutenção</option><option>Instabilidade</option><option>Indisponível</option></Select></div></label></div><Button className="mt-5" disabled={loading||savingSystem||!system.version.trim()||!system.environment.trim()||!system.database.trim()} onClick={()=>void saveSystem()}><Save size={16}/>{savingSystem?"Salvando...":"Salvar configurações"}</Button></Card></>;
}
