import { Bell,FileText,HeartPulse,Save,ShieldAlert } from "lucide-react";
import { useEffect,useState } from "react";
import { Button,Card,Input,Select } from "../components/ui/Common";
import { useAuth } from "../contexts/AuthContext";
import { supabase } from "../services/supabase";
type Row=Record<string,any>;
export function SiteContent(){const[rows,setRows]=useState<Row[]>([]),[saving,setSaving]=useState("");const load=()=>supabase.from("site_content").select("*").order("key").then(({data})=>setRows(data??[]));useEffect(()=>{void load()},[]);const save=async(row:Row)=>{setSaving(row.key);const user=(await supabase.auth.getUser()).data.user;await supabase.from("site_content").update({value:row.value,updated_by:user?.id,updated_at:new Date().toISOString()}).eq("key",row.key);await supabase.from("activity_logs").insert({actor_id:user?.id,action:"site_content.changed",entity_type:"site_content",metadata:{key:row.key}});setSaving("")};return <><Header eyebrow="CMS seguro" title="Conteúdo do Site"/><div className="grid gap-4 lg:grid-cols-2">{rows.map((r,i)=><Card key={r.key}><div className="flex gap-3"><FileText className="text-blue-500"/><div className="flex-1"><b>{r.label}</b><p className="text-xs text-zinc-500">{r.key}</p></div></div><textarea value={r.value} onChange={e=>setRows(v=>v.map((x,j)=>j===i?{...x,value:e.target.value}:x))} maxLength={2000} className="mt-4 min-h-28 w-full rounded-xl border bg-transparent p-3 text-sm dark:border-zinc-700"/><Button disabled={saving===r.key} onClick={()=>void save(r)}><Save size={16}/>Salvar</Button></Card>)}</div></>}
export function AdminNotifications(){const{user}=useAuth();const[rows,setRows]=useState<Row[]>([]),[title,setTitle]=useState(""),[message,setMessage]=useState(""),[type,setType]=useState("information");const load=()=>supabase.from("platform_notifications").select("*").order("created_at",{ascending:false}).then(({data})=>setRows(data??[]));useEffect(()=>{void load()},[]);const create=async()=>{if(!user||title.length<2||message.length<2)return;await supabase.from("platform_notifications").insert({title,message,type,target_type:"all",created_by:user.id});setTitle("");setMessage("");await load()};return <><Header eyebrow="Comunicação global" title="Notificações"/><Card><div className="grid gap-3 md:grid-cols-[1fr_180px]"><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título"/><Select value={type} onChange={e=>setType(e.target.value)}><option value="information">Informação</option><option value="news">Novidade</option><option value="maintenance">Manutenção</option><option value="important">Importante</option></Select></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Mensagem" className="my-3 min-h-24 w-full rounded-xl border bg-transparent p-3 text-sm dark:border-zinc-700"/><Button onClick={()=>void create()}><Bell size={16}/>Publicar para todas as empresas</Button></Card><div className="mt-5 space-y-3">{rows.map(r=><Card key={r.id}><b>{r.title}</b><p className="text-sm text-zinc-500">{r.message}</p><p className="mt-2 text-xs uppercase text-blue-500">{r.type} • {r.active?"ativa":"inativa"}</p></Card>)}</div></>}
export function GlobalSettings(){const[rows,setRows]=useState<Row[]>([]);const load=()=>supabase.from("global_settings").select("*").order("key").then(({data})=>setRows(data??[]));useEffect(()=>{void load()},[]);const save=async()=>{const user=(await supabase.auth.getUser()).data.user;await Promise.all(rows.map(r=>supabase.from("global_settings").update({value:r.value,updated_by:user?.id,updated_at:new Date().toISOString()}).eq("key",r.key)))};return <><Header eyebrow="Plataforma" title="Configurações globais"/><Card><div className="space-y-4">{rows.map((r,i)=><label key={r.key}>{r.key}<Input value={r.value} onChange={e=>setRows(v=>v.map((x,j)=>j===i?{...x,value:e.target.value}:x))}/></label>)}<Button onClick={()=>void save()}><Save size={16}/>Salvar configurações</Button></div></Card></>}
export function AdminSecurity(){const[companies,setCompanies]=useState<Row[]>([]),[profiles,setProfiles]=useState<Row[]>([]);useEffect(()=>{void Promise.all([supabase.from("companies").select("id,name,status"),supabase.from("profiles").select("user_id,full_name,status")]).then(([c,p])=>{setCompanies(c.data??[]);setProfiles(p.data??[])})},[]);return <><Header eyebrow="Controles reais" title="Segurança"/><div className="grid gap-4 md:grid-cols-3"><Metric label="Empresas suspensas" value={companies.filter(c=>c.status==="suspended").length}/><Metric label="Usuários suspensos" value={profiles.filter(p=>p.status==="suspended").length}/><Metric label="Métodos ativos" value="E-mail • Google • Passkeys"/></div><Card className="mt-5"><ShieldAlert className="text-amber-500"/><p className="mt-3 text-sm text-zinc-500">Roles críticas são validadas por RPC e RLS. Tokens, senhas e biometria não são registrados em auditoria.</p></Card></>}
export function SystemHealth(){const[db,setDb]=useState<"checking"|"online"|"error">("checking");useEffect(()=>{void supabase.from("global_settings").select("key").limit(1).then(({error})=>setDb(error?"error":"online"))},[]);return <><Header eyebrow="Estado verificável" title="Saúde do sistema"/><div className="grid gap-4 md:grid-cols-3"><Metric label="Aplicação" value="v1.0.0"/><Metric label="Ambiente" value={import.meta.env.MODE}/><Metric label="Banco de dados" value={db==="checking"?"Verificando...":db==="online"?"Acessível":"Indisponível"}/></div><Card className="mt-5"><HeartPulse className={db==="online"?"text-emerald-500":"text-red-500"}/><p className="mt-3 text-sm text-zinc-500">Esta tela não inventa uptime ou erros: mostra somente informações disponíveis no frontend e uma consulta real ao banco.</p></Card></>}
const Header=({eyebrow,title}:{eyebrow:string;title:string})=><div className="mb-6"><p className="text-sm text-zinc-500">{eyebrow}</p><h2 className="text-3xl font-black">{title}</h2></div>;
const Metric=({label,value}:{label:string;value:string|number})=><Card><p className="text-sm text-zinc-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></Card>;
