import { AlertTriangle, CheckCircle2, Plus, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AmountModal } from "../components/modals/AmountModal";
import { ConfirmModal } from "../components/modals/ConfirmModal";
import { Button, Card, Select } from "../components/ui/Common";
import { useAuth } from "../contexts/AuthContext";
import { useFinance } from "../contexts/FinanceContext";
import { supabase } from "../services/supabase";
import type { CategoryBudget } from "../types";
import { parseLocalDate } from "../utils/dateRanges";
import { formatProtectedCurrency } from "../utils/protectedFormat";
type BudgetRow={id:string;category:string;amount:number|string;month:number;year:number;created_at:string;updated_at:string};
const categories=["Alimentação","Transporte","Moradia","Lazer","Saúde","Educação","Assinaturas","Outros"];
export function Budgets(){
 const {user}=useAuth(),{budget,setBudget,transactions,hiddenValues,notify}=useFinance(),[editing,setEditing]=useState(false),[category,setCategory]=useState(categories[0]),[categoryModal,setCategoryModal]=useState(false),[categoryBudgets,setCategoryBudgets]=useState<CategoryBudget[]>([]),[deleting,setDeleting]=useState<CategoryBudget|null>(null);const now=new Date(),month=now.getMonth()+1,year=now.getFullYear();
 useEffect(()=>{if(!user)return;void supabase.from("category_budgets").select("*").eq("user_id",user.id).eq("month",month).eq("year",year).order("category").then(({data,error})=>{if(error){if(import.meta.env.DEV)console.error("[Vertex Hub]",error.message);return}setCategoryBudgets(((data??[])as BudgetRow[]).map(r=>({id:r.id,category:r.category,amount:Number(r.amount),month:r.month,year:r.year,createdAt:r.created_at,updatedAt:r.updated_at})))})},[user,month,year]);
 const monthExpenses=useMemo(()=>transactions.filter(t=>{const d=parseLocalDate(t.date);return t.type==="expense"&&d.getMonth()+1===month&&d.getFullYear()===year}),[transactions,month,year]),used=monthExpenses.reduce((s,t)=>s+t.amount,0),pct=budget>0?Math.min(100,used/budget*100):0;
 const saveCategory=async(amount:number)=>{if(!user)return;const existing=categoryBudgets.find(b=>b.category===category);const query=existing?supabase.from("category_budgets").update({amount,updated_at:new Date().toISOString()}).eq("id",existing.id).eq("user_id",user.id).select("*").single():supabase.from("category_budgets").insert({user_id:user.id,category,amount,month,year}).select("*").single();const{data,error}=await query;if(error){notify("Não foi possível salvar o orçamento por categoria. Aplique a migration mais recente.","error");return}const r=data as BudgetRow,item={id:r.id,category:r.category,amount:Number(r.amount),month:r.month,year:r.year,createdAt:r.created_at,updatedAt:r.updated_at};setCategoryBudgets(c=>existing?c.map(b=>b.id===item.id?item:b):[...c,item].sort((a,b)=>a.category.localeCompare(b.category)));notify("Orçamento por categoria salvo")};
 const removeCategory=async()=>{if(!user||!deleting)return;const{error}=await supabase.from("category_budgets").delete().eq("id",deleting.id).eq("user_id",user.id);if(error)return notify("Não foi possível excluir o orçamento.","error");setCategoryBudgets(c=>c.filter(b=>b.id!==deleting.id));notify("Orçamento por categoria excluído")};
 return <><div className="mb-6"><p className="text-sm text-zinc-500">Planejamento mensal</p><h2 className="text-3xl font-black">Orçamentos</h2></div><Card><div className="flex items-center gap-3">{pct>90?<AlertTriangle className="text-red-500"/>:<CheckCircle2 className="text-emerald-500"/>}<div><h3 className="font-bold">Orçamento geral</h3><p className="text-xs text-zinc-500">Limite para despesas deste mês</p></div></div>{budget>0?<><p className="mt-8 text-4xl font-black">{formatProtectedCurrency(used,hiddenValues)} <small className="text-sm font-normal text-zinc-500">de {formatProtectedCurrency(budget,hiddenValues)}</small></p><div className="mt-6 h-4 rounded-full bg-zinc-100 dark:bg-zinc-800"><div className={`h-full rounded-full ${pct>90?"bg-red-500":pct>70?"bg-amber-500":"bg-blue-500"}`} style={{width:`${pct}%`}}/></div><div className="mt-3 flex justify-between text-sm"><span>{pct.toFixed(0)}% utilizado</span><b>{formatProtectedCurrency(Math.max(0,budget-used),hiddenValues)} disponível</b></div></>:<p className="my-8 text-zinc-500">Defina seu orçamento mensal para acompanhar seus gastos.</p>}<Button className="mt-5" onClick={()=>setEditing(true)}>Editar limite</Button></Card>
 <div className="mb-4 mt-7 flex items-end justify-between"><div><h3 className="text-xl font-bold">Por categoria</h3><p className="text-sm text-zinc-500">Limites para {now.toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</p></div><div className="flex gap-2"><Select aria-label="Categoria" value={category} onChange={e=>setCategory(e.target.value)} className="w-auto">{categories.map(c=><option key={c}>{c}</option>)}</Select><Button onClick={()=>setCategoryModal(true)}><Plus size={17}/>Definir</Button></div></div>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{categoryBudgets.map(item=>{const spent=monthExpenses.filter(t=>t.category===item.category).reduce((s,t)=>s+t.amount,0),progress=Math.min(100,spent/item.amount*100);return <Card key={item.id}><div className="flex justify-between"><b>{item.category}</b><button aria-label={`Excluir orçamento de ${item.category}`} onClick={()=>setDeleting(item)} className="text-zinc-400 hover:text-red-500"><Trash2 size={17}/></button></div><p className="mt-4 text-xl font-black">{formatProtectedCurrency(spent,hiddenValues)} <small className="inline text-zinc-500">de {formatProtectedCurrency(item.amount,hiddenValues)}</small></p><div className="mt-4 h-2.5 rounded-full bg-zinc-100 dark:bg-zinc-800"><div className={`h-full rounded-full ${progress>=100?"bg-red-500":progress>=70?"bg-amber-500":"bg-blue-500"}`} style={{width:`${progress}%`}}/></div><p className="mt-2 text-xs text-zinc-500">{progress.toFixed(0)}% utilizado • {formatProtectedCurrency(Math.max(0,item.amount-spent),hiddenValues)} restante</p></Card>})}{!categoryBudgets.length&&<Card className="py-10 text-center text-sm text-zinc-500">Nenhum orçamento por categoria.<br/>Selecione uma categoria e defina o primeiro limite.</Card>}</div>
 <AmountModal open={editing} title="Editar orçamento mensal" description="Use zero para remover o limite." initialValue={budget} allowZero onClose={()=>setEditing(false)} onConfirm={setBudget}/><AmountModal open={categoryModal} title={`Orçamento: ${category}`} description="Defina o limite desta categoria para o mês atual." initialValue={categoryBudgets.find(b=>b.category===category)?.amount} onClose={()=>setCategoryModal(false)} onConfirm={saveCategory}/><ConfirmModal open={Boolean(deleting)} title="Excluir orçamento por categoria" description={`O limite de ${deleting?.category??""} será removido apenas deste mês.`} danger confirmLabel="Excluir" onClose={()=>setDeleting(null)} onConfirm={removeCategory}/></>;
}
