import { Plus,Trash2 } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { AmountModal } from "../components/modals/AmountModal";
import { Button,Card,Select } from "../components/ui/Common";
import { useAuth } from "../contexts/AuthContext";
import { useCompany } from "../contexts/CompanyContext";
import { useFinance } from "../contexts/FinanceContext";
import { supabase } from "../services/supabase";
import type { CategoryBudget } from "../types";
import { parseLocalDate } from "../utils/dateRanges";
import { formatProtectedCurrency } from "../utils/protectedFormat";
type Row={id:string;category:string;amount:number|string;month:number;year:number;created_at:string;updated_at:string};
const categories=["Alimentação","Transporte","Moradia","Lazer","Saúde","Educação","Assinaturas","Outros"];
export function Budgets(){const{user}=useAuth(),{activeCompany}=useCompany(),{budget,setBudget,transactions,hiddenValues,notify}=useFinance();const[editing,setEditing]=useState(false),[category,setCategory]=useState(categories[0]),[modal,setModal]=useState(false),[items,setItems]=useState<CategoryBudget[]>([]);const now=new Date(),month=now.getMonth()+1,year=now.getFullYear();
 useEffect(()=>{if(!activeCompany)return;void supabase.from("category_budgets").select("*").eq("company_id",activeCompany.id).eq("month",month).eq("year",year).order("category").then(({data})=>setItems(((data??[])as Row[]).map(r=>({id:r.id,category:r.category,amount:Number(r.amount),month:r.month,year:r.year,createdAt:r.created_at,updatedAt:r.updated_at}))))},[activeCompany,month,year]);
 const expenses=useMemo(()=>transactions.filter(t=>{const d=parseLocalDate(t.date);return t.type==="expense"&&d.getMonth()+1===month&&d.getFullYear()===year}),[transactions,month,year]);const used=expenses.reduce((s,t)=>s+t.amount,0),pct=budget?Math.min(100,used/budget*100):0;
 const save=async(amount:number)=>{if(!user||!activeCompany)return;const existing=items.find(i=>i.category===category);const row={company_id:activeCompany.id,created_by:user.id,user_id:user.id,category,amount,month,year,updated_at:new Date().toISOString()};const q=existing?supabase.from("category_budgets").update(row).eq("id",existing.id).eq("company_id",activeCompany.id).select().single():supabase.from("category_budgets").insert(row).select().single();const{data,error}=await q;if(error)return notify("Não foi possível salvar o orçamento.","error");const r=data as Row,item={id:r.id,category:r.category,amount:Number(r.amount),month:r.month,year:r.year,createdAt:r.created_at,updatedAt:r.updated_at};setItems(v=>existing?v.map(x=>x.id===item.id?item:x):[...v,item]);notify("Orçamento por categoria salvo")};
 const remove=async(item:CategoryBudget)=>{if(!activeCompany)return;const{error}=await supabase.from("category_budgets").delete().eq("id",item.id).eq("company_id",activeCompany.id);if(error)return notify("Não foi possível excluir.","error");setItems(v=>v.filter(x=>x.id!==item.id))};
 return <><div className="mb-6"><p className="text-sm text-zinc-500">Planejamento mensal de {activeCompany?.name}</p><h2 className="text-3xl font-black">Orçamentos</h2></div><Card><h3 className="font-bold">Orçamento geral</h3><p className="mt-6 text-3xl font-black">{formatProtectedCurrency(used,hiddenValues)} <small className="inline text-sm text-zinc-500">de {formatProtectedCurrency(budget,hiddenValues)}</small></p><div className="my-4 h-3 rounded-full bg-zinc-100 dark:bg-zinc-800"><div className="h-full rounded-full bg-blue-500" style={{width:`${pct}%`}}/></div><Button onClick={()=>setEditing(true)}>Editar limite</Button></Card><div className="mb-4 mt-7 flex items-end justify-between"><h3 className="text-xl font-bold">Por categoria</h3><div className="flex gap-2"><Select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</Select><Button onClick={()=>setModal(true)}><Plus size={17}/>Definir</Button></div></div><div className="grid gap-4 md:grid-cols-3">{items.map(item=>{const spent=expenses.filter(t=>t.category===item.category).reduce((s,t)=>s+t.amount,0);return <Card key={item.id}><div className="flex justify-between"><b>{item.category}</b><button onClick={()=>void remove(item)}><Trash2 size={17}/></button></div><p className="mt-4 text-xl font-black">{formatProtectedCurrency(spent,hiddenValues)} <small className="inline text-zinc-500">de {formatProtectedCurrency(item.amount,hiddenValues)}</small></p></Card>})}</div><AmountModal open={editing} title="Editar orçamento mensal" initialValue={budget} allowZero onClose={()=>setEditing(false)} onConfirm={setBudget}/><AmountModal open={modal} title={`Orçamento: ${category}`} initialValue={items.find(i=>i.category===category)?.amount} onClose={()=>setModal(false)} onConfirm={save}/></>}
