import { ArrowDownRight, ArrowUpRight, CalendarDays, Landmark, PiggyBank, TrendingDown, TrendingUp, Wallet } from "lucide-react";
import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useFinance } from "../contexts/FinanceContext";
import type { Transaction } from "../types";
import { formatCurrency } from "../utils/format";
import { TransactionList } from "../components/transactions/TransactionList";
import { Button, Card, Select } from "../components/ui/Common";
const colors=["#3b82f6","#8b5cf6","#f59e0b","#ef4444","#22c55e","#06b6d4","#ec4899","#71717a"];
export function Dashboard({onEdit,setPage}:{onEdit:(t:Transaction)=>void,setPage:(p:"transactions")=>void}) {
 const {transactions,budget,setBudget}=useFinance();const [range,setRange]=useState("month");const [chartMode,setChartMode]=useState("monthly");
 const filtered=useMemo(()=>{const now=new Date(),start=new Date();if(range==="7")start.setDate(now.getDate()-7);else if(range==="30")start.setDate(now.getDate()-30);else if(range==="year")start.setMonth(0,1);else start.setDate(1);return transactions.filter(t=>new Date(`${t.date}T12:00:00`)>=start);},[transactions,range]);
 const income=filtered.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),expense=filtered.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);
 const allIncome=transactions.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),allExpense=transactions.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);
 const categories=Object.entries(filtered.filter(t=>t.type==="expense").reduce<Record<string,number>>((a,t)=>({...a,[t.category]:(a[t.category]||0)+t.amount}),{})).sort((a,b)=>b[1]-a[1]);
 const chartData=useMemo(()=>Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-(5-i));const m=d.getMonth(),y=d.getFullYear();const tx=transactions.filter(t=>{const x=new Date(`${t.date}T12:00:00`);return x.getMonth()===m&&x.getFullYear()===y});return{name:d.toLocaleDateString("pt-BR",{month:"short"}),Receitas:tx.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),Despesas:tx.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0)}}),[transactions]);
 const cards=[[Wallet,"Saldo atual",allIncome-allExpense,"+12,8%","blue"],[TrendingUp,"Receitas do período",income,"+8,2%","green"],[TrendingDown,"Despesas do período",expense,"−4,1%","red"],[PiggyBank,"Economia do período",income-expense,"+18,6%","violet"]] as const;
 const used=Math.min(100,(expense/budget)*100);
 return <><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-zinc-500">Visão consolidada</p><h2 className="text-2xl font-black sm:text-3xl">Painel financeiro</h2></div><label className="flex items-center gap-2 rounded-xl border bg-white px-3 dark:border-zinc-700 dark:bg-zinc-900"><CalendarDays size={17}/><Select className="border-0 bg-transparent" value={range} onChange={e=>setRange(e.target.value)}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="month">Este mês</option><option value="year">Este ano</option></Select></label></div>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon,label,value,delta,color])=><Card key={label} className="group overflow-hidden"><div className="flex items-start justify-between"><span className={`grid size-11 place-items-center rounded-xl bg-${color}-500/10 text-${color}-500`} style={{color:color==="green"?"#22c55e":color==="red"?"#ef4444":color==="violet"?"#8b5cf6":"#3b82f6"}}><Icon/></span><span className="flex items-center rounded-full bg-emerald-500/10 px-2 py-1 text-xs font-bold text-emerald-500"><ArrowUpRight size={13}/>{delta}</span></div><p className="mt-5 text-sm text-zinc-500">{label}</p><p className="mt-1 text-2xl font-black">{formatCurrency(value)}</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800"><i className="block h-full w-2/3 rounded-full bg-blue-500"/></div></Card>)}</section>
 <section className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><Card><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">Receitas e despesas</h3><p className="text-xs text-zinc-500">Evolução dos últimos 6 meses</p></div><Select value={chartMode} onChange={e=>setChartMode(e.target.value)} className="w-auto"><option value="daily">Diário</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></Select></div><div className="h-72"><ResponsiveContainer><AreaChart data={chartData}><defs><linearGradient id="inc" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#22c55e" stopOpacity=".3"/><stop offset="1" stopColor="#22c55e" stopOpacity="0"/></linearGradient><linearGradient id="exp" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#ef4444" stopOpacity=".3"/><stop offset="1" stopColor="#ef4444" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#71717a33"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(v)=>formatCurrency(Number(v))} contentStyle={{borderRadius:12,background:"#18181b",border:"1px solid #3f3f46",color:"#fff"}}/><Legend/><Area type="monotone" dataKey="Receitas" stroke="#22c55e" fill="url(#inc)" strokeWidth={3}/><Area type="monotone" dataKey="Despesas" stroke="#ef4444" fill="url(#exp)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Card>
 <Card><h3 className="font-bold">Gastos por categoria</h3><p className="text-xs text-zinc-500">Distribuição no período</p><div className="h-48"><ResponsiveContainer><PieChart><Pie data={categories.map(([name,value])=>({name,value}))} dataKey="value" innerRadius={52} outerRadius={76} paddingAngle={3}>{categories.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={v=>formatCurrency(Number(v))}/></PieChart></ResponsiveContainer></div><div className="space-y-2">{categories.slice(0,4).map(([name,value],i)=><div className="flex items-center text-xs" key={name}><i className="mr-2 size-2.5 rounded-full" style={{background:colors[i]}}/><span className="flex-1 text-zinc-500">{name}</span><b>{formatCurrency(value)}</b></div>)}</div></Card></section>
 <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_1.7fr]"><Card><div className="flex items-start justify-between"><div><h3 className="font-bold">Orçamento mensal</h3><p className="text-xs text-zinc-500">Acompanhe seu limite</p></div><button onClick={()=>{const v=prompt("Novo limite mensal",String(budget));if(v&&Number(v)>0)setBudget(Number(v))}} className="text-sm font-bold text-blue-500">Editar</button></div><div className="my-7 flex items-end justify-between"><div><p className="text-xs text-zinc-500">Utilizado</p><b className="text-2xl">{formatCurrency(expense)}</b></div><span className={`font-black ${used>90?"text-red-500":used>70?"text-amber-500":"text-emerald-500"}`}>{used.toFixed(0)}%</span></div><div className="h-3 rounded-full bg-zinc-100 dark:bg-zinc-800"><div className={`h-full rounded-full ${used>90?"bg-red-500":used>70?"bg-amber-500":"bg-emerald-500"}`} style={{width:`${used}%`}}/></div><div className="mt-4 flex justify-between text-sm"><span className="text-zinc-500">Limite {formatCurrency(budget)}</span><b>{formatCurrency(Math.max(0,budget-expense))} disponível</b></div></Card>
 <div><div className="mb-3 flex items-center justify-between"><div><h3 className="font-bold">Transações recentes</h3><p className="text-xs text-zinc-500">Últimas movimentações registradas</p></div><Button variant="secondary" onClick={()=>setPage("transactions")}>Ver todas</Button></div><TransactionList items={transactions} onEdit={onEdit} limit={5}/></div></section></>;
}
