import { ArrowDownRight, ArrowUpRight, CalendarDays, PiggyBank, TrendingDown, TrendingUp, Wallet } from "lucide-react";
import { useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AmountModal } from "../components/modals/AmountModal";
import { TransactionList } from "../components/transactions/TransactionList";
import { Button, Card, Select } from "../components/ui/Common";
import { useFinance } from "../contexts/FinanceContext";
import { usePeriodComparison } from "../hooks/usePeriodComparison";
import type { ChartMode, Period, Transaction } from "../types";
import { groupTransactions } from "../utils/dateRanges";
import { formatProtectedCurrency } from "../utils/protectedFormat";
const colors=["#3b82f6","#8b5cf6","#f59e0b","#ef4444","#22c55e","#06b6d4","#ec4899","#71717a"];
export function Dashboard({onEdit,setPage}:{onEdit:(t:Transaction)=>void;setPage:(p:"transactions")=>void}) {
 const {transactions,budget,setBudget,hiddenValues}=useFinance();const [range,setRange]=useState<Period>("month"),[chartMode,setChartMode]=useState<ChartMode>("daily"),[budgetModal,setBudgetModal]=useState(false);
 const {currentItems,current,comparisons,ranges}=usePeriodComparison(transactions,range);
 const categories=useMemo(()=>Object.entries(currentItems.filter(t=>t.type==="expense").reduce<Record<string,number>>((acc,t)=>{acc[t.category]=(acc[t.category]??0)+t.amount;return acc},{})).sort((a,b)=>b[1]-a[1]),[currentItems]);
 const chartData=useMemo(()=>groupTransactions(currentItems,chartMode,ranges.start,ranges.end),[currentItems,chartMode,ranges]);
 const allIncome=transactions.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),allExpense=transactions.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);
 const cardData=[{Icon:Wallet,label:"Saldo atual",value:allIncome-allExpense,comparison:comparisons.balance,kind:"balance"},{Icon:TrendingUp,label:"Receitas do período",value:current.income,comparison:comparisons.income,kind:"income"},{Icon:TrendingDown,label:"Despesas do período",value:current.expense,comparison:comparisons.expense,kind:"expense"},{Icon:PiggyBank,label:"Economia do período",value:current.savings,comparison:comparisons.savings,kind:"savings"}] as const;
 const used=budget>0?Math.min(100,current.expense/budget*100):0;
 const deltaStyle=(kind:string,direction:"up"|"down"|"equal")=>direction==="equal"?"text-zinc-500 bg-zinc-500/10":kind==="expense"?(direction==="up"?"text-red-500 bg-red-500/10":"text-emerald-500 bg-emerald-500/10"):(direction==="up"?"text-emerald-500 bg-emerald-500/10":"text-red-500 bg-red-500/10");
 return <><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-zinc-500">Visão consolidada</p><h2 className="text-2xl font-black sm:text-3xl">Painel financeiro</h2></div><label className="flex items-center gap-2 rounded-xl border bg-white px-3 dark:border-zinc-700 dark:bg-zinc-900"><CalendarDays size={17}/><Select aria-label="Período" className="border-0 bg-transparent" value={range} onChange={e=>setRange(e.target.value as Period)}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="month">Este mês</option><option value="year">Este ano</option></Select></label></div>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cardData.map(({Icon,label,value,comparison,kind})=><Card key={label}><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-blue-500/10 text-blue-500"><Icon/></span><span className={`flex items-center rounded-full px-2 py-1 text-xs font-bold ${deltaStyle(kind,comparison.direction)}`}>{comparison.percentage===null?"Sem comparação":<>{comparison.direction==="up"?<ArrowUpRight size={13}/>:comparison.direction==="down"?<ArrowDownRight size={13}/>:null}{Math.abs(comparison.percentage).toFixed(1)}%</>}</span></div><p className="mt-5 text-sm text-zinc-500">{label}</p><p className="mt-1 text-2xl font-black">{formatProtectedCurrency(value,hiddenValues)}</p></Card>)}</section>
 <section className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><Card><div className="mb-5 flex items-center justify-between gap-3"><div><h3 className="font-bold">Receitas e despesas</h3><p className="text-xs text-zinc-500">Dados reais do período selecionado</p></div><Select value={chartMode} onChange={e=>setChartMode(e.target.value as ChartMode)} className="w-auto"><option value="daily">Diário</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option></Select></div>{chartData.some(x=>x.Receitas||x.Despesas)?<div className="h-72"><ResponsiveContainer><AreaChart data={chartData}><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#71717a33"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={v=>formatProtectedCurrency(Number(v),hiddenValues)} contentStyle={{borderRadius:12,background:"#18181b",border:"1px solid #3f3f46",color:"#fff"}}/><Legend/><Area type="monotone" dataKey="Receitas" stroke="#22c55e" fill="#22c55e22" strokeWidth={3}/><Area type="monotone" dataKey="Despesas" stroke="#ef4444" fill="#ef444422" strokeWidth={3}/></AreaChart></ResponsiveContainer></div>:<div className="grid h-72 place-items-center text-center text-sm text-zinc-500">Sem dados no gráfico.<br/>Adicione uma movimentação neste período.</div>}</Card>
 <Card><h3 className="font-bold">Gastos por categoria</h3><p className="text-xs text-zinc-500">Distribuição no período</p>{categories.length?<><div className="h-48"><ResponsiveContainer><PieChart><Pie data={categories.map(([name,value])=>({name,value}))} dataKey="value" innerRadius={52} outerRadius={76}>{categories.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={v=>formatProtectedCurrency(Number(v),hiddenValues)}/></PieChart></ResponsiveContainer></div><div className="max-h-36 space-y-2 overflow-auto">{categories.map(([name,value],i)=><div className="flex items-center text-xs" key={name}><i className="mr-2 size-2.5 rounded-full" style={{background:colors[i%colors.length]}}/><span className="flex-1 text-zinc-500">{name}</span><b>{hiddenValues?"•••":`${current.expense?((value/current.expense)*100).toFixed(1):0}%`} • {formatProtectedCurrency(value,hiddenValues)}</b></div>)}</div></>:<p className="py-24 text-center text-sm text-zinc-500">Nenhuma despesa registrada neste período.</p>}</Card></section>
 <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_1.7fr]"><Card><div className="flex justify-between"><div><h3 className="font-bold">Orçamento mensal</h3><p className="text-xs text-zinc-500">Acompanhe seu limite</p></div><button onClick={()=>setBudgetModal(true)} className="text-sm font-bold text-blue-500">Editar</button></div>{budget>0?<><div className="my-7 flex items-end justify-between"><b className="text-2xl">{formatProtectedCurrency(current.expense,hiddenValues)}</b><span className={used>90?"font-black text-red-500":"font-black text-emerald-500"}>{used.toFixed(0)}%</span></div><div className="h-3 rounded-full bg-zinc-100 dark:bg-zinc-800"><div className="h-full rounded-full bg-blue-500" style={{width:`${used}%`}}/></div><p className="mt-4 text-sm text-zinc-500">{formatProtectedCurrency(Math.max(0,budget-current.expense),hiddenValues)} disponível</p></>:<p className="py-10 text-sm text-zinc-500">Defina seu orçamento mensal para acompanhar seus gastos.</p>}</Card><div><div className="mb-3 flex justify-between"><h3 className="font-bold">Transações recentes</h3><Button variant="secondary" onClick={()=>setPage("transactions")}>Ver todas</Button></div><TransactionList items={transactions} onEdit={onEdit} limit={5}/></div></section>
 <AmountModal open={budgetModal} title="Editar orçamento mensal" description="Defina o limite geral para suas despesas." initialValue={budget} allowZero onClose={()=>setBudgetModal(false)} onConfirm={setBudget}/></>;
}
