import { Download,Eye,FileUp,Search,Trash2 } from "lucide-react";
import { useEffect,useRef,useState } from "react";
import { Button,Card } from "../components/ui/Common";
import { useAuth } from "../contexts/AuthContext";
import { useCompany } from "../contexts/CompanyContext";
import { usePermissions } from "../hooks/usePermissions";
import { supabase } from "../services/supabase";
type Doc={id:string;file_name:string;storage_path:string;size_bytes:number;mime_type:string;created_at:string};
const allowed=["application/pdf","image/jpeg","image/png","image/webp","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/csv"];
const size=(value:number)=>value<1048576?`${(value/1024).toFixed(1)} KB`:`${(value/1048576).toFixed(1)} MB`;
export function Documents(){
 const{activeCompany}=useCompany(),{user}=useAuth(),permissions=usePermissions(),[docs,setDocs]=useState<Doc[]>([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 const load=async()=>{if(!activeCompany)return;setError("");const{data,error:loadError}=await supabase.from("company_files").select("*").eq("company_id",activeCompany.id).is("deleted_at",null).order("created_at",{ascending:false});if(loadError)return setError("Não foi possível carregar os documentos.");setDocs((data??[]) as Doc[])};
 useEffect(()=>{void load()},[activeCompany?.id]);
 const upload=async(file?:File)=>{if(!permissions.canWrite)return setError("Você não possui permissão para realizar esta ação.");if(!file||!activeCompany||!user)return;if(!allowed.includes(file.type))return setError("Formato de arquivo não permitido.");setBusy(true);setError("");const path=`${activeCompany.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const uploaded=await supabase.storage.from("company-documents").upload(path,file);if(uploaded.error){setBusy(false);return setError("Não foi possível enviar o arquivo.")}const saved=await supabase.from("company_files").insert({company_id:activeCompany.id,user_id:user.id,file_name:file.name,storage_path:path,size_bytes:file.size,mime_type:file.type});if(saved.error){await supabase.storage.from("company-documents").remove([path]);setBusy(false);return setError("Não foi possível concluir o envio.")}setBusy(false);await load()};
 const open=async(document:Doc)=>{const{data}=await supabase.storage.from("company-documents").createSignedUrl(document.storage_path,60);if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener,noreferrer")};
 const remove=async(document:Doc)=>{if(!permissions.canWrite)return;if(!confirm("Enviar documento para a lixeira?"))return;await supabase.from("company_files").update({deleted_at:new Date().toISOString()}).eq("id",document.id).eq("company_id",activeCompany?.id??"");await load()};
 const shown=docs.filter(document=>document.file_name.toLowerCase().includes(query.toLowerCase()));
 return <><header className="mb-6"><p className="text-sm text-zinc-500">Arquivos privados da empresa</p><h2 className="text-3xl font-black">Central de Documentos</h2></header><div className="mb-5 flex flex-wrap gap-3">{permissions.canWrite&&<><input ref={input} type="file" hidden accept=".pdf,.jpg,.jpeg,.png,.webp,.docx,.xlsx,.csv" onChange={event=>void upload(event.target.files?.[0])}/><Button disabled={busy} onClick={()=>input.current?.click()}><FileUp size={17}/>{busy?"Enviando arquivo...":"Enviar arquivo"}</Button></>}<div className="flex min-w-64 flex-1 items-center gap-2 rounded-xl border px-3 dark:border-zinc-700"><Search size={17}/><input className="w-full bg-transparent py-2 outline-none" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Pesquisar documentos..."/></div></div>{permissions.isReadOnly&&<p className="mb-4 text-xs font-semibold text-zinc-500">Acesso somente leitura.</p>}{error&&<Card className="mb-4 text-red-500">{error}</Card>}{!error&&!shown.length?<Card className="text-center"><FileUp className="mx-auto text-blue-500"/><b className="mt-3 block">Nenhum documento disponível.</b></Card>:<div className="space-y-2">{shown.map(document=><Card key={document.id} className="flex items-center gap-3"><div className="min-w-0 flex-1"><b className="block truncate">{document.file_name}</b><span className="text-xs text-zinc-500">{size(document.size_bytes)} • {new Date(document.created_at).toLocaleDateString("pt-BR")}</span></div><button aria-label={`Visualizar ${document.file_name}`} onClick={()=>void open(document)}><Eye/></button><button aria-label={`Baixar ${document.file_name}`} onClick={()=>void open(document)}><Download/></button>{permissions.canWrite&&<button aria-label={`Excluir ${document.file_name}`} className="text-red-500" onClick={()=>void remove(document)}><Trash2/></button>}</Card>)}</div>}</>;
}
