import { Calendar,Flag,Plus,Trash2 } from "lucide-react";
import { useState } from "react";
import { AmountModal } from "../components/modals/AmountModal";
import { ConfirmModal } from "../components/modals/ConfirmModal";
import { Button,Card,Input,Modal } from "../components/ui/Common";
import { useFinance } from "../contexts/FinanceContext";
import { usePermissions } from "../hooks/usePermissions";
import type { Goal } from "../types";
import { formatDate } from "../utils/format";
import { formatProtectedCurrency } from "../utils/protectedFormat";
export function Goals(){
 const{goals,saveGoal,deleteGoal,addToGoal,hiddenValues}=useFinance(),permissions=usePermissions(),[open,setOpen]=useState(false),[adding,setAdding]=useState<Goal|null>(null),[deleting,setDeleting]=useState<Goal|null>(null),[name,setName]=useState(""),[target,setTarget]=useState(""),[deadline,setDeadline]=useState("");
 const submit=async()=>{if(!permissions.canWrite)return;if(name&&Number(target)>0&&deadline){await saveGoal({name,targetAmount:Number(target),currentAmount:0,deadline});setOpen(false);setName("");setTarget("");setDeadline("")}};
 return <><div className="mb-6 flex items-end justify-between"><div><p className="text-sm text-zinc-500">Transforme planos em conquistas</p><h2 className="text-3xl font-black">Metas</h2></div>{permissions.canWrite&&<Button onClick={()=>setOpen(true)}><Plus size={17}/>Nova meta</Button>}</div>{permissions.isReadOnly&&<p className="mb-4 text-xs font-semibold text-zinc-500">Acesso somente leitura.</p>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{goals.map(goal=>{const percentage=goal.targetAmount>0?Math.min(100,goal.currentAmount/goal.targetAmount*100):0;return <Card key={goal.id}><div className="flex justify-between"><span className="grid size-11 place-items-center rounded-xl bg-violet-500/10 text-violet-500"><Flag/></span>{permissions.canWrite&&<button aria-label={`Excluir meta ${goal.name}`} onClick={()=>setDeleting(goal)} className="text-zinc-400 hover:text-red-500"><Trash2 size={18}/></button>}</div><h3 className="mt-5 text-lg font-bold">{goal.name}</h3><p className="mt-1 flex items-center gap-1 text-xs text-zinc-500"><Calendar size={13}/>até {formatDate(goal.deadline)}</p><div className="mt-6 flex items-end justify-between"><b className="text-xl">{formatProtectedCurrency(goal.currentAmount,hiddenValues)}</b><span className="text-sm text-zinc-500">de {formatProtectedCurrency(goal.targetAmount,hiddenValues)}</span></div><div className="mt-3 h-2.5 rounded-full bg-zinc-100 dark:bg-zinc-800"><div className="h-full rounded-full bg-violet-500" style={{width:`${percentage}%`}}/></div><div className="mt-4 flex items-center justify-between"><b className="text-sm text-violet-500">{percentage.toFixed(0)}% concluído</b>{permissions.canWrite&&<Button variant="secondary" onClick={()=>setAdding(goal)}>Adicionar valor</Button>}</div></Card>})}</div>{!goals.length&&<Card className="py-16 text-center"><b>Nenhuma meta cadastrada.</b></Card>}{permissions.canWrite&&open&&<Modal title="Nova meta financeira" onClose={()=>setOpen(false)}><div className="space-y-4"><label>Nome da meta<Input value={name} onChange={event=>setName(event.target.value)}/></label><label>Valor desejado<Input type="number" value={target} onChange={event=>setTarget(event.target.value)}/></label><label>Prazo<Input type="date" value={deadline} onChange={event=>setDeadline(event.target.value)}/></label><Button className="w-full" onClick={()=>void submit()}>Criar meta</Button></div></Modal>}<AmountModal open={permissions.canWrite&&Boolean(adding)} title="Adicionar valor" description={`Informe o aporte para ${adding?.name??"a meta"}.`} onClose={()=>setAdding(null)} onConfirm={value=>adding?addToGoal(adding.id,value):Promise.resolve()}/><ConfirmModal open={permissions.canWrite&&Boolean(deleting)} title="Excluir meta" description={`A meta “${deleting?.name??""}” será removida permanentemente.`} danger confirmLabel="Excluir" onClose={()=>setDeleting(null)} onConfirm={()=>deleting?deleteGoal(deleting.id):Promise.resolve()}/></>;
}
