import { Building2,Check,UserRound } from "lucide-react";
import { useState } from "react";
import { Button,Card,Input } from "../components/ui/Common";
import { useAuth } from "../contexts/AuthContext";
import { useCompany } from "../contexts/CompanyContext";
import { supabase } from "../services/supabase";
import { formatCNPJ,formatCPF,formatPhone,normalizeDocument,normalizePhone,validateCNPJ,validateCPF,validatePhone } from "../utils/brDocuments";
export function Onboarding(){const{user}=useAuth(),{reload}=useCompany();const[step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState("");const[data,setData]=useState({fullName:String(user?.user_metadata.full_name??user?.user_metadata.name??""),phone:"",cpf:"",companyName:"",legalName:"",cnpj:"",companyPhone:"",companyEmail:""});const set=(key:keyof typeof data,value:string)=>setData(d=>({...d,[key]:value}));
 const next=()=>{setError("");if(!data.fullName.trim())return setError("Informe seu nome completo.");if(!validatePhone(data.phone))return setError("Telefone inválido.");if(!validateCPF(data.cpf))return setError("CPF inválido.");setStep(2)};
 const finish=async()=>{setError("");if(!data.companyName.trim())return setError("Informe o nome da empresa.");if(!validateCNPJ(data.cnpj))return setError("CNPJ inválido.");if(data.companyPhone&&!validatePhone(data.companyPhone))return setError("Telefone empresarial inválido.");setBusy(true);const{error:e}=await supabase.rpc("complete_company_onboarding",{p_full_name:data.fullName.trim(),p_phone:normalizePhone(data.phone),p_cpf:normalizeDocument(data.cpf),p_company_name:data.companyName.trim(),p_legal_name:data.legalName.trim(),p_cnpj:normalizeDocument(data.cnpj),p_company_phone:normalizePhone(data.companyPhone),p_company_email:data.companyEmail.trim().toLowerCase()});setBusy(false);if(e){setError(e.code==="23505"?"CPF ou CNPJ já cadastrado.":"Não foi possível concluir o cadastro. Revise os dados e tente novamente.");return}await reload()};
 return <main className="min-h-screen bg-zinc-950 p-5 text-white"><div className="mx-auto max-w-2xl py-10"><p className="text-sm font-bold text-blue-400">VERTEX HUB • PRIMEIRO ACESSO</p><h1 className="mt-2 text-3xl font-black">Vamos preparar seu ambiente</h1><p className="mt-2 text-zinc-400">Etapa {step} de 2 — {step===1?"Seus dados":"Sua empresa"}</p><div className="my-7 flex gap-2"><i className="h-2 flex-1 rounded-full bg-blue-600"/><i className={`h-2 flex-1 rounded-full ${step===2?"bg-blue-600":"bg-zinc-800"}`}/></div><Card className="border-zinc-800 bg-zinc-900">{step===1?<div className="space-y-4"><div className="mb-5 flex items-center gap-3"><UserRound className="text-blue-400"/><div><h2 className="font-bold">Seus dados</h2><p className="text-xs text-zinc-500">Usados para identificar o responsável.</p></div></div><label>Nome completo<Input value={data.fullName} onChange={e=>set("fullName",e.target.value)}/></label><label>E-mail<Input disabled value={user?.email??""}/></label><label>Telefone<Input inputMode="numeric" value={formatPhone(data.phone)} onChange={e=>set("phone",normalizePhone(e.target.value))} placeholder="(61) 9 9999-0000"/></label><label>CPF<Input inputMode="numeric" value={formatCPF(data.cpf)} onChange={e=>set("cpf",normalizeDocument(e.target.value).slice(0,11))} placeholder="000.000.000-00"/></label><Button className="w-full" onClick={next}>Continuar</Button></div>:<div className="space-y-4"><div className="mb-5 flex items-center gap-3"><Building2 className="text-violet-400"/><div><h2 className="font-bold">Sua empresa</h2><p className="text-xs text-zinc-500">Este será seu ambiente financeiro isolado.</p></div></div><label>Nome fantasia<Input value={data.companyName} onChange={e=>set("companyName",e.target.value)}/></label><label>Razão social (opcional)<Input value={data.legalName} onChange={e=>set("legalName",e.target.value)}/></label><label>CNPJ<Input inputMode="numeric" value={formatCNPJ(data.cnpj)} onChange={e=>set("cnpj",normalizeDocument(e.target.value).slice(0,14))}/></label><div className="grid gap-4 sm:grid-cols-2"><label>Telefone empresarial<Input inputMode="numeric" value={formatPhone(data.companyPhone)} onChange={e=>set("companyPhone",normalizePhone(e.target.value))}/></label><label>E-mail empresarial<Input type="email" value={data.companyEmail} onChange={e=>set("companyEmail",e.target.value)}/></label></div><div className="flex gap-3"><Button variant="secondary" onClick={()=>setStep(1)}>Voltar</Button><Button disabled={busy} className="flex-1" onClick={()=>void finish()}><Check size={18}/>{busy?"Criando ambiente...":"Concluir cadastro"}</Button></div></div>}{error&&<p role="alert" className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-400">{error}</p>}</Card></div></main>}
