import { Building2,Check,KeyRound,LogOut,Search,UserRound } from "lucide-react";
import { useEffect,useMemo,useState } from "react";
import { OfficialLogo } from "../components/brand/OfficialLogo";
import { Button,Card,Input } from "../components/ui/Common";
import { useAuth } from "../contexts/AuthContext";
import { useCompany } from "../contexts/CompanyContext";
import { supabase } from "../services/supabase";
import type { AccountType } from "../types";
import { formatCNPJ,formatPhone,normalizeDocument,normalizePhone,validateCNPJ,validatePhone } from "../utils/brDocuments";

type CompanyOption={id:string;name:string};
const activationMessage=(code?:string)=>({
  invalid_activation_key:"Chave de ativação inválida.",activation_key_unavailable:"Esta chave já foi utilizada ou cancelada.",activation_key_expired:"Esta chave de ativação expirou.",activation_key_wrong_type:"Esta chave não é válida para o tipo de conta selecionado.",activation_key_wrong_company:"Esta chave de ativação não pertence à empresa selecionada.",company_information_missing:"Preencha os dados da empresa antes de ativar.",cnpj_already_registered:"Este CNPJ já está cadastrado.",
}[code??""]??"Não foi possível ativar a conta. Confira os dados e tente novamente.");

export function Onboarding({onCompleted}:{onCompleted:()=>Promise<void>}){
 const{signOut}=useAuth(),{profile,reload}=useCompany();
 const[type,setType]=useState<AccountType|undefined>(profile?.accountType),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(false);
 const[query,setQuery]=useState(""),[companies,setCompanies]=useState<CompanyOption[]>([]),[selected,setSelected]=useState(profile?.selectedCompanyId??""),[activationKey,setActivationKey]=useState("");
 const[company,setCompany]=useState({name:"",legalName:"",cnpj:"",phone:"",email:""});
 const state=profile?.onboardingState??"account_created";
 const stage=state==="activation_required"?4:state==="account_type_selected"||state==="company_information"||state==="company_selected"?3:2;
 const labels=useMemo(()=>["Conta","Tipo de conta","Empresa","Ativação"],[]);
 useEffect(()=>{if(profile?.accountType)setType(profile.accountType)},[profile?.accountType]);
 useEffect(()=>{if(type!=="employee"||stage<3)return;const timer=setTimeout(async()=>{const{data}=await supabase.rpc("search_onboarding_companies",{p_query:query});setCompanies((data??[]) as CompanyOption[])},250);return()=>clearTimeout(timer)},[query,type,stage]);
 const chooseType=async(value:AccountType)=>{setBusy(true);setError("");const{error:e}=await supabase.rpc("set_onboarding_account_type",{p_account_type:value});setBusy(false);if(e)return setError("Não foi possível salvar o tipo de conta.");setType(value);await reload()};
 const saveCompany=async()=>{setError("");if(!company.name.trim())return setError("Informe o nome fantasia.");if(!validateCNPJ(company.cnpj))return setError("Informe um CNPJ válido.");if(company.phone&&!validatePhone(company.phone))return setError("Informe um telefone válido.");setBusy(true);const{error:e}=await supabase.rpc("save_onboarding_company",{p_name:company.name.trim(),p_legal_name:company.legalName.trim(),p_cnpj:normalizeDocument(company.cnpj),p_phone:normalizePhone(company.phone),p_email:company.email.trim().toLowerCase()});setBusy(false);if(e)return setError(e.message.includes("cnpj_already")?"Este CNPJ já está cadastrado.":"Não foi possível salvar os dados da empresa.");await reload()};
 const saveSelection=async()=>{if(!selected)return setError("Selecione uma empresa.");setBusy(true);setError("");const{error:e}=await supabase.rpc("select_onboarding_company",{p_company_id:selected});setBusy(false);if(e)return setError("Não foi possível selecionar esta empresa.");await reload()};
 const activate=async(e:React.FormEvent)=>{e.preventDefault();if(busy||activationKey.trim().length<8)return;setBusy(true);setError("");const result=await supabase.rpc("complete_activation_onboarding",{p_activation_key:activationKey.trim().toUpperCase()});if(result.error){setBusy(false);return setError(activationMessage(result.error.message))}setSuccess(true);await reload();await onCompleted();setBusy(false)};
 return <main className="min-h-screen bg-zinc-100 p-4 text-zinc-950 transition dark:bg-[#07090d] dark:text-white sm:p-7"><div className="mx-auto max-w-3xl py-5 sm:py-10"><header className="flex items-center justify-between"><div className="flex items-center gap-3"><OfficialLogo className="size-12"/><div><b>Vertex Hub</b><p className="text-xs text-zinc-500">Configuração da sua conta</p></div></div><button onClick={()=>void signOut()} className="flex items-center gap-2 text-sm text-zinc-500 hover:text-red-500"><LogOut size={16}/>Sair</button></header>
 <div className="my-8 grid grid-cols-4 gap-2">{labels.map((label,index)=>{const number=index+1,active=number<=stage;return <div key={label} className="text-center"><div className="flex items-center"><i className={`h-px flex-1 ${index===0?"opacity-0":active?"bg-blue-500":"bg-zinc-300 dark:bg-zinc-800"}`}/><span className={`grid size-8 place-items-center rounded-full text-xs font-bold ${active?"bg-blue-600 text-white":"bg-zinc-200 text-zinc-500 dark:bg-zinc-800"}`}>{number<stage?<Check size={15}/>:number}</span><i className={`h-px flex-1 ${index===3?"opacity-0":number<stage?"bg-blue-500":"bg-zinc-300 dark:bg-zinc-800"}`}/></div><span className="mt-2 block text-[11px] sm:text-xs">{label}</span></div>})}</div>
 {stage===2&&<><div className="mb-6 text-center"><h1 className="text-3xl font-black">Como você utilizará o Vertex Hub?</h1><p className="mt-2 text-zinc-500">Escolha o caminho que corresponde à sua conta.</p></div><div className="grid gap-4 sm:grid-cols-2"><button disabled={busy} onClick={()=>void chooseType("company")} className="group rounded-3xl border bg-white p-7 text-left shadow-sm transition hover:-translate-y-1 hover:border-blue-500 hover:shadow-xl dark:border-zinc-800 dark:bg-zinc-900"><Building2 className="text-blue-500" size={34}/><h2 className="mt-5 text-xl font-black">Empresa</h2><p className="mt-2 text-sm text-zinc-500">Cadastre e gerencie sua empresa no Vertex Hub.</p></button><button disabled={busy} onClick={()=>void chooseType("employee")} className="group rounded-3xl border bg-white p-7 text-left shadow-sm transition hover:-translate-y-1 hover:border-violet-500 hover:shadow-xl dark:border-zinc-800 dark:bg-zinc-900"><UserRound className="text-violet-500" size={34}/><h2 className="mt-5 text-xl font-black">Funcionário</h2><p className="mt-2 text-sm text-zinc-500">Entre em uma empresa que já utiliza o Vertex Hub.</p></button></div></>}
 {stage===3&&type==="company"&&<Card><h1 className="text-2xl font-black">Cadastre sua empresa</h1><p className="mt-1 text-sm text-zinc-500">O acesso só será liberado após a ativação.</p><div className="mt-6 space-y-4"><label>Nome fantasia<Input value={company.name} onChange={e=>setCompany(x=>({...x,name:e.target.value}))}/></label><label>Razão social<Input value={company.legalName} onChange={e=>setCompany(x=>({...x,legalName:e.target.value}))}/></label><label>CNPJ<Input inputMode="numeric" value={formatCNPJ(company.cnpj)} onChange={e=>setCompany(x=>({...x,cnpj:normalizeDocument(e.target.value).slice(0,14)}))}/></label><div className="grid gap-4 sm:grid-cols-2"><label>Telefone<Input value={formatPhone(company.phone)} onChange={e=>setCompany(x=>({...x,phone:normalizePhone(e.target.value)}))}/></label><label>E-mail empresarial<Input type="email" value={company.email} onChange={e=>setCompany(x=>({...x,email:e.target.value}))}/></label></div><Button disabled={busy} className="w-full" onClick={()=>void saveCompany()}>{busy?"Salvando...":"Continuar"}</Button></div></Card>}
 {stage===3&&type==="employee"&&<Card><h1 className="text-2xl font-black">Selecione sua empresa</h1><p className="mt-1 text-sm text-zinc-500">Você não criará uma empresa neste fluxo.</p><div className="relative mt-6"><Search className="absolute left-3 top-3.5 text-zinc-500" size={17}/><Input className="pl-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar empresa..."/></div><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{companies.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`w-full rounded-xl border p-3 text-left text-sm transition ${selected===c.id?"border-blue-500 bg-blue-500/10":"border-zinc-200 hover:border-blue-400 dark:border-zinc-700"}`}><b>{c.name}</b></button>)}</div><Button disabled={busy||!selected} className="mt-5 w-full" onClick={()=>void saveSelection()}>{busy?"Salvando...":"Continuar"}</Button></Card>}
 {stage===4&&<Card className="mx-auto max-w-xl"><div className="grid size-12 place-items-center rounded-2xl bg-blue-600/10 text-blue-500"><KeyRound/></div><h1 className="mt-4 text-3xl font-black">Ative sua conta</h1><p className="mt-2 text-zinc-500">Insira a chave fornecida pela Vertex ou pelo administrador da sua empresa.</p><form className="mt-6 space-y-4" onSubmit={activate}><Input autoComplete="one-time-code" className="text-center font-mono uppercase tracking-wider" value={activationKey} onChange={e=>setActivationKey(e.target.value)} placeholder="VX-XXXXX-XXXXX-XXXXX-XXXXX"/><Button className="w-full" disabled={busy||activationKey.trim().length<8}>{busy?"Validando...":"Ativar conta"}</Button></form>{success&&<p className="mt-4 rounded-xl bg-emerald-500/10 p-3 text-sm font-semibold text-emerald-500">✓ Conta ativada com sucesso.</p>}</Card>}
 {error&&<p role="alert" className="mx-auto mt-4 max-w-xl rounded-xl bg-red-500/10 p-3 text-sm text-red-500">{error}</p>}</div></main>
}
