import { Check,ChevronLeft,Moon,Sun } from "lucide-react";
import { useEffect,useState } from "react";
import { Button,Card } from "../components/ui/Common";
import { useTheme } from "../hooks/useTheme";
import { useI18n,type Locale,type Market } from "../i18n";
import { supabase } from "../services/supabase";

type Plan={plan:string;display_name:string;description:string;monthly_price:number|null;user_limit:number|null};
type Limit={plan:string;max_users:number|null;storage_limit_bytes:number|null;max_file_size_bytes:number|null;max_units:number|null;audit_retention_days:number|null;features:Record<string,boolean>};
const order:Record<string,number>={free:0,start:1,growth:2,prime:3,enterprise:4};
const labels:Record<Locale,{users:string;storage:string;file:string;units:string;audit:string;dashboard:string;crm:string;tasks:string;documents:string;custom:string;export:string;customValue:string}>={
 "pt-BR":{users:"usuários",storage:"de armazenamento",file:"por arquivo",units:"unidades",audit:"de auditoria",dashboard:"Dashboard financeiro",crm:"CRM e clientes",tasks:"Tarefas e calendário",documents:"Central de documentos",custom:"Campos personalizados",export:"Exportações avançadas",customValue:"Personalizado"},
 en:{users:"users",storage:"storage",file:"per file",units:"units",audit:"audit history",dashboard:"Financial dashboard",crm:"CRM and customers",tasks:"Tasks and calendar",documents:"Document center",custom:"Custom fields",export:"Advanced exports",customValue:"Custom"},
 es:{users:"usuarios",storage:"de almacenamiento",file:"por archivo",units:"unidades",audit:"de auditoría",dashboard:"Panel financiero",crm:"CRM y clientes",tasks:"Tareas y calendario",documents:"Central de documentos",custom:"Campos personalizados",export:"Exportaciones avanzadas",customValue:"Personalizado"}
};
const bytes=(n:number|null,custom:string)=>n==null?custom:n>=1073741824?`${n/1073741824} GB`:`${Math.round(n/1048576)} MB`;

export function PublicPlans({onBack,onLogin,onRegister}:{onBack:()=>void;onLogin:()=>void;onRegister:()=>void}){
 const{theme,toggle}=useTheme(),{locale,setLocale,market,setMarket,t}=useI18n(),[plans,setPlans]=useState<Plan[]>([]),[limits,setLimits]=useState<Limit[]>([]),[prices,setPrices]=useState<any[]>([]),[error,setError]=useState(false);
 useEffect(()=>{void Promise.all([supabase.from("plan_settings").select("plan,display_name,description,monthly_price,user_limit"),supabase.from("plan_limits").select("*"),supabase.from("plan_prices").select("plan,market,currency,monthly_price").eq("active",true)]).then(([a,b,c])=>{if(a.error||b.error||c.error){setError(true);return}setPlans(((a.data??[]) as Plan[]).sort((x,y)=>order[x.plan]-order[y.plan]));setLimits((b.data??[]) as Limit[]);setPrices(c.data??[])})},[]);
 const price=(p:Plan)=>{if(p.plan==="enterprise")return t("consult");const regional=prices.find(x=>x.plan===p.plan&&x.market===market),value=regional?.monthly_price??(market==="BR"?p.monthly_price:null);if(value==null)return t("consult");return new Intl.NumberFormat(locale,{style:"currency",currency:regional?.currency??"BRL"}).format(value)+(Number(value)>0?t("month"):"")};
 const benefits=(p:Plan)=>{const l=limits.find(x=>x.plan===p.plan),x=labels[locale];if(!l)return[];const custom=p.plan==="enterprise";const list=[`${custom?x.customValue:l.max_users} ${x.users}`,`${bytes(l.storage_limit_bytes,x.customValue)} ${x.storage}`,`${bytes(l.max_file_size_bytes,x.customValue)} ${x.file}`,`${custom?x.customValue:l.max_units} ${x.units}`,x.dashboard,x.crm,x.tasks,x.documents];if(l.features?.custom_fields||custom)list.push(x.custom);if(l.features?.export_xlsx||l.features?.full_export||custom)list.push(x.export);if(l.audit_retention_days)list.push(`${l.audit_retention_days} dias ${x.audit}`);return list};
 return <main className="page-transition min-h-screen bg-zinc-50 p-5 text-zinc-950 dark:bg-zinc-950 dark:text-white"><header className="mx-auto flex max-w-7xl flex-wrap items-center gap-3 py-4"><Button variant="secondary" onClick={onBack}><ChevronLeft/>{t("back")}</Button><b className="text-xl">Vertex Hub 2.0</b><div className="ml-auto flex gap-2"><select aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value as Locale)} className="rounded-xl border bg-transparent px-2"><option value="pt-BR">PT</option><option value="en">EN</option><option value="es">ES</option></select><select aria-label="Market" value={market} onChange={e=>setMarket(e.target.value as Market)} className="rounded-xl border bg-transparent px-2"><option value="BR">Brasil • BRL</option><option value="INTL">International • USD</option></select><button aria-label="Alternar tema" onClick={toggle}>{theme==="dark"?<Sun/>:<Moon/>}</button></div></header><section className="mx-auto max-w-7xl py-14 text-center"><h1 className="text-4xl font-black">{t("planTitle")}</h1><p className="mt-3 text-zinc-500">{t("free")}</p>{error?<Card className="mx-auto mt-8 max-w-xl text-red-500">Não foi possível carregar os planos.</Card>:<div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{plans.map(p=><Card key={p.plan} className={`flex flex-col text-left ${p.plan==="growth"?"border-blue-500 ring-2 ring-blue-500/10":""}`}>{p.plan==="growth"&&<span className="mb-2 text-xs font-bold text-blue-500">{t("popular")}</span>}<b className="uppercase text-blue-500">{p.display_name}</b><p className="mt-3 text-2xl font-black">{price(p)}</p><p className="my-4 min-h-12 text-sm text-zinc-500">{p.description}</p><ul className="flex-1 space-y-2 text-sm">{benefits(p).map(v=><li className="flex gap-2" key={v}><Check size={17} className="shrink-0 text-emerald-500"/>{v}</li>)}</ul><Button className="mt-5" onClick={onRegister}>{p.plan==="free"?t("free"):p.plan==="enterprise"?t("consult"):t("register")}</Button></Card>)}</div>}<Button variant="secondary" className="mt-8" onClick={onLogin}>{t("login")}</Button></section></main>
}
