import { Printer, TrendingDown, TrendingUp, Wallet } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button, Card } from "../components/ui/Common";
import { useFinance } from "../contexts/FinanceContext";
import { formatCurrency } from "../utils/format";
export function Reports(){
 const {transactions}=useFinance();const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);const tx=transactions.filter(t=>{const x=new Date(`${t.date}T12:00:00`);return x.getMonth()===d.getMonth()&&x.getFullYear()===d.getFullYear()});return{name:d.toLocaleDateString("pt-BR",{month:"short"}),income:tx.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),expense:tx.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0)}});const income=months.reduce((s,m)=>s+m.income,0),expense=months.reduce((s,m)=>s+m.expense,0),cat=Object.entries(transactions.filter(t=>t.type==="expense").reduce<Record<string,number>>((a,t)=>({...a,[t.category]:(a[t.category]||0)+t.amount}),{})).sort((a,b)=>b[1]-a[1])[0];
 const stats=[{Icon:TrendingUp,label:"Receitas",value:income,color:"text-emerald-500"},{Icon:TrendingDown,label:"Despesas",value:expense,color:"text-red-500"},{Icon:Wallet,label:"Saldo",value:income-expense,color:"text-blue-500"},{Icon:TrendingDown,label:"Média mensal",value:expense/6,color:"text-violet-500"}];
 return <><div className="mb-6 flex items-end justify-between"><div><p className="text-sm text-zinc-500">Análises e tendências</p><h2 className="text-3xl font-black">Relatórios</h2></div><Button variant="secondary" onClick={()=>window.print()}><Printer size={17}/>Imprimir</Button></div><div className="grid gap-4 md:grid-cols-4">{stats.map(({Icon,label,value,color})=><Card key={label}><Icon className={color}/><p className="mt-4 text-xs text-zinc-500">{label}</p><b className="text-xl">{formatCurrency(value)}</b></Card>)}</div><Card className="mt-5"><h3 className="font-bold">Comparativo mensal</h3><p className="mb-5 text-xs text-zinc-500">Receitas e despesas nos últimos seis meses</p><div className="h-80"><ResponsiveContainer><BarChart data={months}><CartesianGrid vertical={false} stroke="#71717a33"/><XAxis dataKey="name" axisLine={false}/><YAxis hide/><Tooltip formatter={v=>formatCurrency(Number(v))}/><Bar dataKey="income" name="Receitas" fill="#22c55e" radius={[6,6,0,0]}/><Bar dataKey="expense" name="Despesas" fill="#ef4444" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card className="mt-5"><h3 className="font-bold">Resumo financeiro</h3><p className="mt-3 text-sm text-zinc-500">Sua maior categoria de gasto é <b className="text-zinc-900 dark:text-white">{cat?.[0]??"—"}</b>, com {formatCurrency(cat?.[1]??0)}. A taxa de economia do período é de <b className="text-emerald-500">{income?((income-expense)/income*100).toFixed(1):0}%</b>.</p></Card></>;
}
