import { Download, FilterX, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { TransactionList } from "../components/transactions/TransactionList";
import { Button, Card, Input, Select } from "../components/ui/Common";
import { useFinance } from "../contexts/FinanceContext";
import type { Transaction } from "../types";
export function Transactions({onEdit}:{onEdit:(t:Transaction)=>void}) {
 const {transactions}=useFinance();const [search,setSearch]=useState(""),[type,setType]=useState("all"),[category,setCategory]=useState("all"),[status,setStatus]=useState("all"),[payment,setPayment]=useState("all"),[min,setMin]=useState(""),[max,setMax]=useState(""),[sort,setSort]=useState("date-desc"),[page,setPage]=useState(1);
 const filtered=useMemo(()=>transactions.filter(t=>t.description.toLowerCase().includes(search.toLowerCase())&&(type==="all"||t.type===type)&&(category==="all"||t.category===category)&&(status==="all"||t.status===status)&&(payment==="all"||t.paymentMethod===payment)&&(!min||t.amount>=Number(min))&&(!max||t.amount<=Number(max))).sort((a,b)=>sort==="value-desc"?b.amount-a.amount:sort==="value-asc"?a.amount-b.amount:sort==="date-asc"?a.date.localeCompare(b.date):b.date.localeCompare(a.date)),[transactions,search,type,category,status,payment,min,max,sort]);
 const pageSize=8,pages=Math.max(1,Math.ceil(filtered.length/pageSize)),shown=filtered.slice((page-1)*pageSize,page*pageSize);
 const clear=()=>{setSearch("");setType("all");setCategory("all");setStatus("all");setPayment("all");setMin("");setMax("");setPage(1)};
 const csv=()=>{const rows=[["Descrição","Valor","Tipo","Categoria","Data","Pagamento","Status"],...filtered.map(t=>[t.description,t.amount,t.type,t.category,t.date,t.paymentMethod,t.status])];const blob=new Blob(["\ufeff"+rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(";")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="transacoes-fintrack.csv";a.click();URL.revokeObjectURL(a.href)};
 const categories=[...new Set(transactions.map(t=>t.category))],payments=[...new Set(transactions.map(t=>t.paymentMethod))];
 return <><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-zinc-500">Gerencie suas movimentações</p><h2 className="text-3xl font-black">Transações</h2></div><Button variant="secondary" onClick={csv}><Download size={17}/>Exportar CSV</Button></div>
 <Card className="mb-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="relative sm:col-span-2"><Search className="absolute left-3 top-3 text-zinc-400" size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por descrição..." className="pl-10"/></label><Select value={type} onChange={e=>setType(e.target.value)}><option value="all">Todos os tipos</option><option value="income">Receitas</option><option value="expense">Despesas</option></Select><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas as categorias</option>{categories.map(x=><option key={x}>{x}</option>)}</Select><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos os status</option><option value="paid">Pago</option><option value="pending">Pendente</option><option value="scheduled">Agendado</option></Select><Select value={payment} onChange={e=>setPayment(e.target.value)}><option value="all">Todos os pagamentos</option>{payments.map(x=><option key={x}>{x}</option>)}</Select><div className="flex gap-2"><Input type="number" placeholder="Valor mín." value={min} onChange={e=>setMin(e.target.value)}/><Input type="number" placeholder="Valor máx." value={max} onChange={e=>setMax(e.target.value)}/></div><div className="flex gap-2"><Select value={sort} onChange={e=>setSort(e.target.value)}><option value="date-desc">Mais recentes</option><option value="date-asc">Mais antigas</option><option value="value-desc">Maior valor</option><option value="value-asc">Menor valor</option></Select><Button variant="secondary" onClick={clear} title="Limpar filtros"><FilterX size={18}/></Button></div></div></Card>
 <div className="mb-3 text-sm text-zinc-500"><b className="text-zinc-900 dark:text-white">{filtered.length}</b> resultados encontrados</div><TransactionList items={shown} onEdit={onEdit}/><div className="mt-4 flex items-center justify-between text-sm"><span>Página {page} de {pages}</span><div className="flex gap-2"><Button variant="secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Anterior</Button><Button variant="secondary" disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Próxima</Button></div></div></>;
}
