import { Bell, CheckCheck } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { FinancialNotification, Page } from "../../types";
export function NotificationCenter({items,onNavigate}:{items:FinancialNotification[];onNavigate:(page:Page)=>void}) {
 const [open,setOpen]=useState(false),[read,setRead]=useState<string[]>(()=>JSON.parse(localStorage.getItem("vertex-hub-read-notifications")??"[]") as string[]);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false)};const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};document.addEventListener("mousedown",close);document.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",key)}},[]);
 const unread=items.filter(i=>!read.includes(i.id)).length;const mark=(ids:string[])=>{setRead(ids);localStorage.setItem("vertex-hub-read-notifications",JSON.stringify(ids))};
 return <div className="relative" ref={ref}><button aria-label={`Notificações${unread?`, ${unread} não lidas`:""}`} onClick={()=>setOpen(v=>!v)} className="relative rounded-xl border bg-white p-2.5 dark:border-zinc-700 dark:bg-zinc-900"><Bell size={19}/>{unread>0&&<i className="absolute right-2 top-2 size-2 rounded-full bg-red-500"/>}</button>{open&&<div className="fixed left-3 right-3 top-20 z-50 max-h-[70vh] overflow-auto rounded-2xl border bg-white p-3 shadow-2xl dark:border-zinc-700 dark:bg-zinc-900 sm:absolute sm:left-auto sm:right-0 sm:top-12 sm:w-96"><div className="flex items-center justify-between p-2"><b>Notificações</b><button className="flex items-center gap-1 text-xs text-blue-500" onClick={()=>mark(items.map(i=>i.id))}><CheckCheck size={15}/>Marcar todas como lidas</button></div>{items.length?items.map(item=><button key={item.id} onClick={()=>{mark([...new Set([...read,item.id])]);setOpen(false);onNavigate(item.page)}} className="block w-full rounded-xl p-3 text-left hover:bg-zinc-100 dark:hover:bg-zinc-800"><span className="flex items-center gap-2 font-semibold">{!read.includes(item.id)&&<i className="size-2 rounded-full bg-blue-500"/>}{item.title}</span><small className="text-zinc-500">{item.description}</small></button>):<p className="p-8 text-center text-sm text-zinc-500">Nenhuma notificação no momento.</p>}</div>}</div>;
}
