import { Search } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { Goal, Page, Transaction } from "../../types";
export function GlobalSearch({transactions,goals,onNavigate}:{transactions:Transaction[];goals:Goal[];onNavigate:(page:Page)=>void}) {
 const [query,setQuery]=useState(""),[open,setOpen]=useState(false);const ref=useRef<HTMLDivElement>(null);
 const results=useMemo(()=>{const q=query.trim().toLocaleLowerCase("pt-BR");if(!q)return[];const tx=transactions.filter(t=>[t.description,t.category,t.paymentMethod,t.status,String(t.amount)].some(v=>v.toLocaleLowerCase("pt-BR").includes(q))).slice(0,6).map(t=>({id:t.id,type:"Transação",title:t.description,detail:`${t.category} • ${t.paymentMethod}`,page:"transactions" as Page}));const gs=goals.filter(g=>[g.name,String(g.targetAmount)].some(v=>v.toLocaleLowerCase("pt-BR").includes(q))).slice(0,4).map(g=>({id:g.id,type:"Meta",title:g.name,detail:"Meta financeira",page:"goals" as Page}));return[...tx,...gs].slice(0,8)},[query,transactions,goals]);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false)};const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setOpen(false);setQuery("")}};document.addEventListener("mousedown",close);document.addEventListener("keydown",key);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",key)}},[]);
 return <div ref={ref} className="relative hidden md:block"><label className="relative block"><span className="sr-only">Pesquisa global</span><Search className="absolute left-3 top-2.5 text-zinc-400" size={18}/><input value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} className="h-10 w-56 rounded-xl border bg-white pl-10 text-sm dark:border-zinc-700 dark:bg-zinc-900" placeholder="Pesquisar"/></label>{open&&query&&<div className="absolute right-0 top-12 z-50 w-80 rounded-2xl border bg-white p-2 shadow-2xl dark:border-zinc-700 dark:bg-zinc-900">{results.length?results.map(r=><button key={`${r.type}-${r.id}`} onClick={()=>{onNavigate(r.page);setOpen(false);setQuery("")}} className="block w-full rounded-xl p-3 text-left hover:bg-zinc-100 dark:hover:bg-zinc-800"><span className="text-xs font-bold text-blue-500">{r.type}</span><p className="font-semibold">{r.title}</p><small className="text-zinc-500">{r.detail}</small></button>):<p className="p-6 text-center text-sm text-zinc-500">Nenhum resultado encontrado.</p>}</div>}</div>;
}
