import { useEffect,useState } from "react";
import { useAuth } from "../../contexts/AuthContext";
import { supabase } from "../../services/supabase";
import { TermsContent } from "../legal/TermsContent";
import { Button,Card,Input,Modal } from "../ui/Common";
const strong=/(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}/;
export function AccountRequirements({children}:{children:React.ReactNode}){const{user}=useAuth();const[loading,setLoading]=useState(true),[accepted,setAccepted]=useState(false),[mustChange,setMustChange]=useState(false),[checked,setChecked]=useState(false),[show,setShow]=useState(false),[password,setPassword]=useState(""),[error,setError]=useState("");useEffect(()=>{if(!user)return;void Promise.all([supabase.from("terms_acceptances").select("id").eq("user_id",user.id).eq("terms_type","usage").eq("terms_version","1.0").limit(1),supabase.from("profiles").select("must_change_password").eq("user_id",user.id).single()]).then(([t,p])=>{setAccepted(Boolean(t.data?.length));setMustChange(Boolean(p.data?.must_change_password));setLoading(false)})},[user]);if(loading)return <div className="grid min-h-screen place-items-center bg-zinc-950 text-white">Verificando sua conta...</div>;
 if(!accepted)return <main className="grid min-h-screen place-items-center bg-zinc-950 p-5 text-white"><Card className="max-w-xl border-zinc-800 bg-zinc-900"><h1 className="text-2xl font-black">Antes de continuar</h1><p className="mt-2 text-sm text-zinc-400">Leia e aceite os Termos de Uso e Serviço do Vertex Hub.</p><label className="mt-6 flex items-start gap-3"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)} className="mt-1"/><span>Li e aceito os <button type="button" onClick={()=>setShow(true)} className="text-blue-400 underline">Termos de Uso e Serviço</button>.</span></label><Button disabled={!checked} className="mt-5 w-full" onClick={async()=>{const{error:e}=await supabase.rpc("accept_terms",{p_type:"usage",p_version:"1.0",p_company_id:null});if(e)setError("Não foi possível registrar o aceite.");else setAccepted(true)}}>Aceitar e continuar</Button>{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}</Card>{show&&<Modal title="Termos de Uso e Serviço do Vertex Hub" onClose={()=>setShow(false)}><TermsContent/></Modal>}</main>;
 if(mustChange)return <main className="grid min-h-screen place-items-center bg-zinc-950 p-5 text-white"><Card className="w-full max-w-md border-zinc-800 bg-zinc-900"><h1 className="text-2xl font-black">Crie sua senha pessoal</h1><p className="mt-2 text-sm text-zinc-400">A senha inicial deve ser substituída antes de continuar.</p><label className="mt-5">Nova senha<Input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="mt-2 text-xs text-zinc-500">8+ caracteres, maiúscula, minúscula, número e símbolo.</p><Button className="mt-5 w-full" disabled={!strong.test(password)} onClick={async()=>{const{error:e}=await supabase.auth.updateUser({password});if(e)return setError("Não foi possível alterar a senha.");const{error:r}=await supabase.rpc("complete_password_change");if(r)return setError("A senha mudou, mas não foi possível concluir o primeiro acesso.");setMustChange(false)}}>Salvar nova senha</Button>{error&&<p className="mt-3 text-sm text-red-400">{error}</p>}</Card></main>;
 return children}
