import { ShieldCheck } from "lucide-react";
import { useCallback,useEffect,useState } from "react";
import { supabase } from "../../services/supabase";
import { Button,Card,Input } from "../ui/Common";
import {mfaEnrollmentMessage} from "../../utils/mfaErrors";

type Factor={id:string;status?:string;friendly_name?:string};
export function MfaGate({children,superAdmin}:{children:React.ReactNode;superAdmin:boolean}){
 const[loading,setLoading]=useState(true),[required,setRequired]=useState(false),[verified,setVerified]=useState(false),[factor,setFactor]=useState<Factor>(),[qr,setQr]=useState(""),[secret,setSecret]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{const[{data:ctx,error:contextError},{data:factors,error:factorsError},{data:aal,error:aalError}]=await Promise.all([supabase.rpc("get_my_security_context"),supabase.auth.mfa.listFactors(),supabase.auth.mfa.getAuthenticatorAssuranceLevel()]);const row=ctx?.[0];const mustUseMfa=superAdmin||Boolean(row?.mfa_required);if(contextError||factorsError||aalError){setRequired(mustUseMfa);setVerified(false);setError("A proteção MFA ainda não foi configurada no Supabase. Acesso administrativo bloqueado por segurança.");setLoading(false);return}const totp=factors?.totp?.find(x=>x.status==="verified") as Factor|undefined;setRequired(mustUseMfa);setVerified(!mustUseMfa||aal?.currentLevel==="aal2");setFactor(totp);setLoading(false)},[superAdmin]);
 useEffect(()=>{void refresh()},[refresh]);
 const enroll=async()=>{setBusy(true);setError("");const listed=await supabase.auth.mfa.listFactors();for(const old of ((listed.data as any)?.all??[]).filter((x:Factor)=>x.status==="unverified"))await supabase.auth.mfa.unenroll({factorId:old.id});const{data,error:e}=await supabase.auth.mfa.enroll({factorType:"totp",friendlyName:`Vertex Hub ${Date.now()}`});setBusy(false);if(e)return setError(mfaEnrollmentMessage(e));setFactor(data as unknown as Factor);setQr(data.totp.qr_code);setSecret(data.totp.secret)};
 const verify=async()=>{if(!factor||!/^[0-9]{6}$/.test(code))return setError("Digite os 6 números do aplicativo autenticador.");setBusy(true);setError("");const{data:challenge,error:c}=await supabase.auth.mfa.challenge({factorId:factor.id});if(c){setBusy(false);return setError("Não foi possível criar o desafio.")}const{error:v}=await supabase.auth.mfa.verify({factorId:factor.id,challengeId:challenge.id,code});setBusy(false);if(v)return setError("Código inválido ou expirado. Verifique seu aplicativo autenticador e tente novamente.");await supabase.rpc("log_mfa_event",{p_action:factor.status==="verified"?"mfa.verified":"mfa.enrolled"});await refresh()};
 if(loading)return <div className="grid min-h-screen place-items-center bg-zinc-950 text-white">Verificando segurança...</div>;
 if(!required||verified)return <>{children}</>;
 const enrolled=factor?.status==="verified";
 return <main className="grid min-h-screen place-items-center bg-zinc-950 p-5 text-white"><Card className="w-full max-w-md border-zinc-800 bg-zinc-900"><ShieldCheck className="text-blue-500" size={34}/><h1 className="mt-4 text-2xl font-black">{enrolled?"Verificação em duas etapas":"Proteja sua conta"}</h1><p className="mt-2 text-sm text-zinc-400">{enrolled?"Digite o código de 6 dígitos gerado pelo seu aplicativo autenticador.":"Contas Super Admin exigem autenticação de dois fatores."}</p>{!factor&&<Button className="mt-6 w-full" disabled={busy} onClick={()=>void enroll()}>Configurar autenticação de dois fatores</Button>}{qr&&<div className="mt-5"><img className="mx-auto rounded-xl bg-white p-3" src={qr} alt="QR Code TOTP"/><p className="mt-3 break-all rounded-xl bg-zinc-950 p-3 text-xs">Chave manual: {secret}</p></div>}{factor&&<form className="mt-5" onSubmit={e=>{e.preventDefault();void verify()}}><Input autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} className="text-center text-2xl tracking-[.5em]" aria-label="Código de seis dígitos"/><Button className="mt-4 w-full" disabled={busy||code.length!==6}>{busy?"Verificando...":"Verificar"}</Button></form>}{error&&<p className="mt-3 rounded-xl bg-red-500/10 p-3 text-sm text-red-400">{error}</p>}<p className="mt-5 text-xs text-zinc-500">Se perdeu o autenticador, solicite a recuperação de acesso pelo procedimento administrativo documentado.</p></Card></main>
}
